<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_9Wz_ADGTEfCkYdaGFVhtZg" name="MyDiagram" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_Hdk6ADGcEfC-4Z9zH4y95A" name="Verificação dos produtos recebidos">
      <elements xmi:type="process:Lane" xmi:id="_IDg4oDGcEfC-4Z9zH4y95A" name="Técnico de área de operações" actor="_2XLAcDGgEfCnSJk-yp4Knw">
        <elements xmi:type="process:XORGateway" xmi:id="_-dAXwDGjEfC-n5Sky3geQg" name="Cliente ou stock?" outgoing="_C5oUEjGkEfC-n5Sky3geQg _DvbTpzGkEfC-n5Sky3geQg" incoming="_II5gcEIaEfCOhu7W5Z33XQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-dAXwjGjEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-dAXwTGjEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-dAXwzGjEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_DvaskDGkEfC-n5Sky3geQg" name="Produto para entrega" incoming="_DvbTpzGkEfC-n5Sky3geQg" outgoingMessages="_LodmkDyTEfCJUObNuNZMMQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DvbToTGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DvbToDGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DvbTojGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_Loc_gDyTEfCJUObNuNZMMQ" name="Msg">
            <correlation xmi:type="process:Correlation" xmi:id="_Loc_gTyTEfCJUObNuNZMMQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_Loc_gjyTEfCJUObNuNZMMQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_Loc_gzyTEfCJUObNuNZMMQ" name="Venda de produto" content="Venda de produto" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_Loc_hDyTEfCJUObNuNZMMQ" name="Produto para entrega" content="Produto para entrega" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_Loc_hTyTEfCJUObNuNZMMQ"/>
          </events>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_1klxoDyQEfCJUObNuNZMMQ" name="Produto para armazenamento" incoming="_C5oUEjGkEfC-n5Sky3geQg" outgoingMessages="_HeOUAE1YEfCIS7Qdd8ccrg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C5ntAjGkEfC-n5Sky3geQg" name="ProdutoArmazenamento" content="ProdutoArmazenamento" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C5ntATGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C5ntAzGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_Sy6bEDyTEfCJUObNuNZMMQ" name="MsgArmazenamento">
            <correlation xmi:type="process:Correlation" xmi:id="_Sy6bETyTEfCJUObNuNZMMQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_Sy6bEjyTEfCJUObNuNZMMQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_bTtGIU1XEfCIS7Qdd8ccrg" name="Armazenamento de produto" content="Armazenamento de produto" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_bTtGIE1XEfCIS7Qdd8ccrg" name="Produto para armazenamento" content="Produto para armazenamento"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_Sy6bFTyTEfCJUObNuNZMMQ"/>
          </events>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_j027EEIjEfCOhu7W5Z33XQ" name="Escolher para onde vai o produto" outgoing="_II5gcEIaEfCOhu7W5Z33XQ" incoming="__VzoADGjEfC-n5Sky3geQg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FAygAUIaEfCOhu7W5Z33XQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FAygAkIaEfCOhu7W5Z33XQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FAygA0IaEfCOhu7W5Z33XQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_VVTVQExrEfCNq_Z_7Oph1Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_VVTVQUxrEfCNq_Z_7Oph1Q" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WIPOEExrEfCNq_Z_7Oph1Q" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_VVTVQkxrEfCNq_Z_7Oph1Q" name="encomendasInput.destino" content="encomendasInput?.destino" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_bcy38ExrEfCNq_Z_7Oph1Q" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_VVTVQ0xrEfCNq_Z_7Oph1Q" type="JAVA_METHOD" expression="setDestino">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FAygCkIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FAygC0IaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FAygDEIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FAygDUIaEfCOhu7W5Z33XQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FAygDkIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_j027GkIjEfCOhu7W5Z33XQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_S3Ib8ExmEfCNq_Z_7Oph1Q" name="newForm11" content="518be76e-2b97-4a45-a631-1a6c9abc769b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_j027GUIjEfCOhu7W5Z33XQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_cdyDkExaEfCNq_Z_7Oph1Q" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_cdyDkUxaEfCNq_Z_7Oph1Q" name="destino" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_j027HEIjEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_EToUgEIZEfCOhu7W5Z33XQ" name="Devolver produtos e documentos" outgoing="_m694gDGdEfC-4Z9zH4y95A" incoming="_lvinMDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dY4eQTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dY4eQDGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dY4eQjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dY4eQzGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dY4eRDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dY4eRTGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dY4eRzGdEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dY4eRjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EToUikIZEfCOhu7W5Z33XQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_xslEYEIZEfCOhu7W5Z33XQ" name="DevolverProdutos" content="06d6c0bc-3213-48f9-859e-03b3f62f146f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EToUiUIZEfCOhu7W5Z33XQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EToUjEIZEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_JCXGgDGcEfC-4Z9zH4y95A" name="Serviços administrativos" actor="_QG9VMDGdEfC-4Z9zH4y95A">
        <elements xmi:type="process:StartEvent" xmi:id="_21aYcDGcEfC-4Z9zH4y95A" name="Produtos do fornecedor" outgoing="_6pz3IDGcEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_21aYcjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_21aYcTGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_21aYczGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_5vY2QDGcEfC-4Z9zH4y95A" name="Gateway 1" outgoing="_BdZDwDGdEfC-4Z9zH4y95A _CWgdEDGdEfC-4Z9zH4y95A _Cxl2kDGdEfC-4Z9zH4y95A" incoming="_6pz3IDGcEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5vY2QjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5vY2QTGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5vY2QzGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IN0OsDGdEfC-4Z9zH4y95A" name="Verificar  concordância encomenda-documento" outgoing="_V0Ny8DGdEfC-4Z9zH4y95A" incoming="_BdZDwDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_78j4cjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_78j4cTGcEfC-4Z9zH4y95A" name="dynamicDescription()" content="'Clicar na checkbox em baixo caso se verifique a concordância entre a encomenda recebida e o o documento do Fornecedor'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_78j4czGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_WvGtYjyfEfCfw76yGlE_oQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_WvGtYzyfEfCfw76yGlE_oQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WvGtZDyfEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_WvGtZTyfEfCfw76yGlE_oQ" name="encomendasInput.concordancia" content="encomendasInput?.concordancia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_WvGtZjyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_WvGtZzyfEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setConcordancia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_78j4dDGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_78j4dTGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_78j4djGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_78j4eDGcEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_78j4dzGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IN0OujGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_M5i2IDyiEfCfw76yGlE_oQ" name="1verificarConcordancia" content="613953a5-134d-4024-853a-9a5b22be8a31" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IN0OuTGdEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_WvGtYDyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_WvGtYTyfEfCfw76yGlE_oQ" name="concordancia" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IN0OvDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_RAuOwDGdEfC-4Z9zH4y95A" name="Verificar quantidade" outgoing="_VBadADGdEfC-4Z9zH4y95A" incoming="_CWgdEDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGAjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGATGcEfC-4Z9zH4y95A" name="dynamicDescription()" content="'Clicar na checkbox em baixo caso se verifique a quantidade correta do produto'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGAzGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_YuQhsjyfEfCfw76yGlE_oQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_YuQhszyfEfCfw76yGlE_oQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YuQhtDyfEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_YuQhtTyfEfCfw76yGlE_oQ" name="encomendasInput.quantidade" content="encomendasInput?.quantidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_YuQhtjyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_YuQhtzyfEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setQuantidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8vnGBDGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnGBTGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnGBjGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnGCDGcEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8vnGBzGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_RAuOyjGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_pRHIoDyiEfCfw76yGlE_oQ" name="1verificarQuantidade" content="69cd46b8-2116-41a0-b0ab-d41ca7f7d380" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_RAuOyTGdEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_YuQhsDyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_YuQhsTyfEfCfw76yGlE_oQ" name="quantidade" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_RAuOzDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Rfa88DGdEfC-4Z9zH4y95A" name="Verificar estado do produto" outgoing="_WfPs8DGdEfC-4Z9zH4y95A" incoming="_Cxl2kDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9xidETGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9xidEDGcEfC-4Z9zH4y95A" name="dynamicDescription()" content="'Clicar na checkbox em baixo caso o produto se apresente em aparente estado de conformidade (não apresente embalagem danificada ou outros problemas aparentes)'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9xidEjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_ESu74jyjEfCfw76yGlE_oQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ESu74zyjEfCfw76yGlE_oQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ESu75DyjEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ESu75TyjEfCfw76yGlE_oQ" name="encomendasInput.aparencia" content="encomendasInput?.aparencia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ESu75jyjEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ESu75zyjEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setAparencia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9xidEzGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9xidFDGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9xidFTGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9xidFzGcEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9xidFjGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Rfa8-jGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_KupPYDyjEfCfw76yGlE_oQ" name="1verificarEstado" content="c4325f5f-7f3f-46b8-abe1-32eb81b99a57" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Rfa8-TGdEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_ESu74DyjEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ESu74TyjEfCfw76yGlE_oQ" name="aparencia" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Rfa8_DGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_UaHzgDGdEfC-4Z9zH4y95A" name="Gateway 2" outgoing="_lDeycDGdEfC-4Z9zH4y95A" incoming="_VBadADGdEfC-4Z9zH4y95A _V0Ny8DGdEfC-4Z9zH4y95A _WfPs8DGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UaHzgjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UaHzgTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UaHzgzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ajKOUDGdEfC-4Z9zH4y95A" name="Tudo Correto?" outgoing="_lZ_N8DGdEfC-4Z9zH4y95A __VzoADGjEfC-n5Sky3geQg" incoming="_lDeycDGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ajKOUjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ajKOUTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ajKOUzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_cAKX0DGdEfC-4Z9zH4y95A" name="Gateway 3" outgoing="_lvinMDGdEfC-4Z9zH4y95A _mGqGsDGdEfC-4Z9zH4y95A" incoming="_lZ_N8DGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cAKX0jGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cAKX0TGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cAKX0zGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_eUr_MDGdEfC-4Z9zH4y95A" name="Gateway4" outgoing="_nYSGoDGdEfC-4Z9zH4y95A" incoming="_meCr8DGdEfC-4Z9zH4y95A _m694gDGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eUsmQDGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eUr_MTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eUsmQTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_fbLGIDGdEfC-4Z9zH4y95A" name="Produto devolvido" incoming="_nYSGoDGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fbLGIjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fbLGITGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fbLGIzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_o7qk8DGdEfC-4Z9zH4y95A" name="Preencher nota de não conformidade" outgoing="_meCr8DGdEfC-4Z9zH4y95A" incoming="_mGqGsDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dAFjwjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dAFjwTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dAFjwzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dAFjxDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dAFjxTGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dAFjxjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dAFjyDGdEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dAFjxzGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_o7qk-jGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_tLT4oEIZEfCOhu7W5Z33XQ" name="NotaConformidade" content="f30e0b1b-24f1-493c-b0b8-24e7a6b33685" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_o7qk-TGdEfC-4Z9zH4y95A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_o7qk_DGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ie2ZYDycEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Tp7FJDyfEfCfw76yGlE_oQ" name="initEncomendas()" content="def encomendasVar = new com.company.model.Encomendas()&#xD;&#xA;encomendasVar.concordancia = encomendasInput?.concordancia&#xD;&#xA;encomendasVar.aparencia = encomendasInput?.aparencia&#xD;&#xA;encomendasVar.quantidade = encomendasInput?.quantidade&#xD;&#xA;return encomendasVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Encomendas">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Tp7FJTyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_jgdnYDycEfCfw76yGlE_oQ" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento">
        <defaultValue xmi:type="expression:Expression" xmi:id="_UituUjyfEfCfw76yGlE_oQ" name="initArmazenamento()" content="def armazenamentoVar = new com.company.model.Armazenamento()&#xD;&#xA;armazenamentoVar.id_produto = armazenamentoInput?.id_produto&#xD;&#xA;return armazenamentoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Armazenamento">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_UituUzyfEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Hdk6EDGcEfC-4Z9zH4y95A">
        <targetForm xmi:type="expression:Expression" xmi:id="_fscQcE3lEfCX2JYZsK0L_A" name="InstatiationFormVerificacao" content="93ee8599-b36e-4b1f-a23d-b5c352bb6c93" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Hdk6EjGcEfC-4Z9zH4y95A">
        <targetForm xmi:type="expression:Expression" xmi:id="_fr_5oE3nEfCX2JYZsK0L_A" name="OverviewInitiator" content="471fbe5f-b4b8-4ac9-821d-024a696dd358" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6pz3IDGcEfC-4Z9zH4y95A" target="_5vY2QDGcEfC-4Z9zH4y95A" source="_21aYcDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6pz3ITGcEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_6pz3IjGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BdZDwDGdEfC-4Z9zH4y95A" target="_IN0OsDGdEfC-4Z9zH4y95A" source="_5vY2QDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BdZDwTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_BdZDwjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CWgdEDGdEfC-4Z9zH4y95A" target="_RAuOwDGdEfC-4Z9zH4y95A" source="_5vY2QDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CWgdETGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_CWgdEjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Cxl2kDGdEfC-4Z9zH4y95A" target="_Rfa88DGdEfC-4Z9zH4y95A" source="_5vY2QDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Cxl2kTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Cxl2kjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VBadADGdEfC-4Z9zH4y95A" target="_UaHzgDGdEfC-4Z9zH4y95A" source="_RAuOwDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VBadATGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_VBadAjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V0Ny8DGdEfC-4Z9zH4y95A" target="_UaHzgDGdEfC-4Z9zH4y95A" source="_IN0OsDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V0Ny8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_V0Ny8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WfPs8DGdEfC-4Z9zH4y95A" target="_UaHzgDGdEfC-4Z9zH4y95A" source="_Rfa88DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WfPs8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_WfPs8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lDeycDGdEfC-4Z9zH4y95A" target="_ajKOUDGdEfC-4Z9zH4y95A" source="_UaHzgDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lDeycTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lDeycjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lZ_N8DGdEfC-4Z9zH4y95A" name="Não" target="_cAKX0DGdEfC-4Z9zH4y95A" source="_ajKOUDGdEfC-4Z9zH4y95A" isDefault="true" conditionType="DECISION_TABLE">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lZ_N8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lZ_N8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lvinMDGdEfC-4Z9zH4y95A" target="_EToUgEIZEfCOhu7W5Z33XQ" source="_cAKX0DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lvinMTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lvinMjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mGqGsDGdEfC-4Z9zH4y95A" target="_o7qk8DGdEfC-4Z9zH4y95A" source="_cAKX0DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mGqGsTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_mGqGsjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_meCr8DGdEfC-4Z9zH4y95A" target="_eUr_MDGdEfC-4Z9zH4y95A" source="_o7qk8DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_meCr8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_meCr8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_m694gDGdEfC-4Z9zH4y95A" target="_eUr_MDGdEfC-4Z9zH4y95A" source="_EToUgEIZEfCOhu7W5Z33XQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_m694gTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_m694gjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nYSGoDGdEfC-4Z9zH4y95A" target="_fbLGIDGdEfC-4Z9zH4y95A" source="_eUr_MDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nYSGoTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_nYSGojGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__VzoADGjEfC-n5Sky3geQg" name="Sim" target="_j027EEIjEfCOhu7W5Z33XQ" source="_ajKOUDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__VzoATGjEfC-n5Sky3geQg"/>
        <condition xmi:type="expression:Expression" xmi:id="__VzoAjGjEfC-n5Sky3geQg" name="VerificaçãoEncomenda" content="encomendas.concordancia == true &amp;&amp;&#xD;&#xA;encomendas.aparencia == true &amp;&amp;&#xD;&#xA;encomendas.quantidade == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pl2n8EIfEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_C5oUEjGkEfC-n5Sky3geQg" name="Stock" target="_1klxoDyQEfCJUObNuNZMMQ" source="_-dAXwDGjEfC-n5Sky3geQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_C5oUEzGkEfC-n5Sky3geQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_C5oUFDGkEfC-n5Sky3geQg" name="stock" content="encomendas.destino == true&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_VHCYAE3lEfCX2JYZsK0L_A" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DvbTpzGkEfC-n5Sky3geQg" name="Cliente" target="_DvaskDGkEfC-n5Sky3geQg" source="_-dAXwDGjEfC-n5Sky3geQg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DvbTqDGkEfC-n5Sky3geQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_DvbTqTGkEfC-n5Sky3geQg" name="cliente" content="encomendas.destino == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TCr6oE3lEfCX2JYZsK0L_A" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_II5gcEIaEfCOhu7W5Z33XQ" target="_-dAXwDGjEfC-n5Sky3geQg" source="_j027EEIjEfCOhu7W5Z33XQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_II6HgEIaEfCOhu7W5Z33XQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_II6HgUIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QG9VMDGdEfC-4Z9zH4y95A" name="Serviços administrativos" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_2XLAcDGgEfCnSJk-yp4Knw" name="Técnico de área de operações"/>
      <contract xmi:type="process:Contract" xmi:id="_Hdk6FDGcEfC-4Z9zH4y95A">
        <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FIDyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas">
          <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FITyfEfCfw76yGlE_oQ" name="concordancia" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FIjyfEfCfw76yGlE_oQ" name="aparencia" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FIzyfEfCfw76yGlE_oQ" name="quantidade" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_h6ZWEEyCEfCNq_Z_7Oph1Q" name="destino" type="BOOLEAN">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_h6ZWEUyCEfCNq_Z_7Oph1Q"/>
          </inputs>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_UituUDyfEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento">
          <inputs xmi:type="process:ContractInput" xmi:id="_UituUTyfEfCfw76yGlE_oQ" name="id_produto" type="INTEGER"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6ATGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6AjGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6AzGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6BDGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6BTGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6BjGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6BzGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6CDGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6CTGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6CjGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6CzGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6DDGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6DTGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6DjGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6DzGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="__vl0YE1XEfCIS7Qdd8ccrg" name="Armazenamento de produto">
      <elements xmi:type="process:Lane" xmi:id="_C1E-oE1YEfCIS7Qdd8ccrg" name="Tecnico de area de operações" actor="_PgIU8E1YEfCIS7Qdd8ccrg">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_GkLGkE1YEfCIS7Qdd8ccrg" name="Produto para armazenamento" outgoing="_JeuMIE1YEfCIS7Qdd8ccrg" event="MsgArmazenamento" incomingMessag="_HeOUAE1YEfCIS7Qdd8ccrg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GkLGkk1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GkLGkU1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GkLGk01YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_K0dQAE1YEfCIS7Qdd8ccrg" name="Produto armazenado" incoming="_K0fsQE1YEfCIS7Qdd8ccrg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_K0d3EU1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_K0d3EE1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_K0d3Ek1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_NU_6IE1YEfCIS7Qdd8ccrg" name="Atribuir etiqueta &quot;S&quot;" outgoing="_KBuyk01YEfCIS7Qdd8ccrg" incoming="_JeuMIE1YEfCIS7Qdd8ccrg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Jes-AU1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Jes-AE1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Jes-Ak1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_j2VHKU1aEfCIS7Qdd8ccrg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j2VHKk1aEfCIS7Qdd8ccrg" name="armazenamento" content="armazenamento" type="TYPE_VARIABLE" returnType="com.company.model.Armazenamento">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_j2VHK01aEfCIS7Qdd8ccrg" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j2VHLE1aEfCIS7Qdd8ccrg" name="armazenamentoInput.etiquetaS" content="armazenamentoInput?.etiquetaS" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_j2VHLU1aEfCIS7Qdd8ccrg" name="armazenamentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_j2VHLk1aEfCIS7Qdd8ccrg" type="JAVA_METHOD" expression="setEtiquetaS">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Jes-A01YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Jes-BE1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Jes-BU1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Jes-B01YEfCIS7Qdd8ccrg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Jes-Bk1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NVAhOU1YEfCIS7Qdd8ccrg">
            <targetForm xmi:type="expression:Expression" xmi:id="_lR9-sE1aEfCIS7Qdd8ccrg" name="newEtiquetaS" content="21c05006-f708-4289-8364-3a97f863c500" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NVAhOE1YEfCIS7Qdd8ccrg">
            <inputs xmi:type="process:ContractInput" xmi:id="_j2UgEE1aEfCIS7Qdd8ccrg" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_j2VHIE1aEfCIS7Qdd8ccrg" name="id_produto" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_j2VHIU1aEfCIS7Qdd8ccrg" name="etiquetaS" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_j2VHIk1aEfCIS7Qdd8ccrg" name="armazenarStock" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NVAhO01YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_N76JIE1YEfCIS7Qdd8ccrg" name="Armazenar em stock" outgoing="_K0fsQE1YEfCIS7Qdd8ccrg" incoming="_KBuyk01YEfCIS7Qdd8ccrg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KBuLgk1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KBuLgU1YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KBuLg01YEfCIS7Qdd8ccrg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_qp_MUE1aEfCIS7Qdd8ccrg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qp_MUU1aEfCIS7Qdd8ccrg" name="armazenamento" content="armazenamento" type="TYPE_VARIABLE" returnType="com.company.model.Armazenamento">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qp_MUk1aEfCIS7Qdd8ccrg" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qp_MU01aEfCIS7Qdd8ccrg" name="armazenamentoInput.armazenarStock" content="armazenamentoInput?.armazenarStock" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qp_MVE1aEfCIS7Qdd8ccrg" name="armazenamentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qp_MVU1aEfCIS7Qdd8ccrg" type="JAVA_METHOD" expression="setArmazenarStock">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KBuLhE1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KBuLhU1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KBuLhk1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KBuLiE1YEfCIS7Qdd8ccrg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KBuLh01YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_N76wMk1YEfCIS7Qdd8ccrg">
            <targetForm xmi:type="expression:Expression" xmi:id="_sNPHsE1aEfCIS7Qdd8ccrg" name="newArmazenamento" content="d73a71cc-c739-48c0-b837-aac2628c3b42" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_N76wMU1YEfCIS7Qdd8ccrg">
            <inputs xmi:type="process:ContractInput" xmi:id="_qp_MQE1aEfCIS7Qdd8ccrg" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_qp_MQU1aEfCIS7Qdd8ccrg" name="id_produto" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qp_MQk1aEfCIS7Qdd8ccrg" name="etiquetaS" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qp_MQ01aEfCIS7Qdd8ccrg" name="armazenarStock" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_N76wNE1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_igwbUE1aEfCIS7Qdd8ccrg" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento">
        <defaultValue xmi:type="expression:Expression" xmi:id="_igwbUU1aEfCIS7Qdd8ccrg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="__zRagE1XEfCIS7Qdd8ccrg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_yrGS0E3lEfCX2JYZsK0L_A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="__zRagk1XEfCIS7Qdd8ccrg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="__zRag01XEfCIS7Qdd8ccrg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JeuMIE1YEfCIS7Qdd8ccrg" target="_NU_6IE1YEfCIS7Qdd8ccrg" source="_GkLGkE1YEfCIS7Qdd8ccrg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JeuMIU1YEfCIS7Qdd8ccrg"/>
        <condition xmi:type="expression:Expression" xmi:id="_JeuMIk1YEfCIS7Qdd8ccrg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KBuyk01YEfCIS7Qdd8ccrg" target="_N76JIE1YEfCIS7Qdd8ccrg" source="_NU_6IE1YEfCIS7Qdd8ccrg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KBuylE1YEfCIS7Qdd8ccrg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KBuylU1YEfCIS7Qdd8ccrg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K0fsQE1YEfCIS7Qdd8ccrg" target="_K0dQAE1YEfCIS7Qdd8ccrg" source="_N76JIE1YEfCIS7Qdd8ccrg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K0fsQU1YEfCIS7Qdd8ccrg"/>
        <condition xmi:type="expression:Expression" xmi:id="_K0fsQk1YEfCIS7Qdd8ccrg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_PgIU8E1YEfCIS7Qdd8ccrg" name="Tecnico de area de operacoes"/>
      <contract xmi:type="process:Contract" xmi:id="__zRahE1XEfCIS7Qdd8ccrg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="__zQzcE1XEfCIS7Qdd8ccrg">
        <name xmi:type="expression:Expression" xmi:id="__zQzcU1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="__zQzck1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="__zQzc01XEfCIS7Qdd8ccrg">
        <name xmi:type="expression:Expression" xmi:id="__zQzdE1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="__zQzdU1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="__zQzdk1XEfCIS7Qdd8ccrg">
        <name xmi:type="expression:Expression" xmi:id="__zQzd01XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="__zQzeE1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="__zQzeU1XEfCIS7Qdd8ccrg">
        <name xmi:type="expression:Expression" xmi:id="__zQzek1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="__zQze01XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="__zQzfE1XEfCIS7Qdd8ccrg">
        <name xmi:type="expression:Expression" xmi:id="__zQzfU1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="__zQzfk1XEfCIS7Qdd8ccrg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_9Wz_ATGTEfCkYdaGFVhtZg" name="Venda de produto">
      <elements xmi:type="process:Lane" xmi:id="_9Wz_AjGTEfCkYdaGFVhtZg" name="Employee lane" actor="_9Wz_GzGTEfCkYdaGFVhtZg">
        <elements xmi:type="process:Task" xmi:id="_9Wz_BzGTEfCkYdaGFVhtZg" name="Atribuir etiqueta &quot;P&quot;" outgoing="_yBJVADGYEfC-4Z9zH4y95A" incoming="_S6TRcDGbEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9Wz_CDGTEfCkYdaGFVhtZg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9Wz_CTGTEfCkYdaGFVhtZg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9Wz_CjGTEfCkYdaGFVhtZg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_IfX65E1LEfCIS7Qdd8ccrg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IfX65U1LEfCIS7Qdd8ccrg" name="vendas" content="vendas" type="TYPE_VARIABLE" returnType="com.company.model.Vendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IfX65k1LEfCIS7Qdd8ccrg" name="vendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Vendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IfX6501LEfCIS7Qdd8ccrg" name="vendasInput.etiquetaP" content="vendasInput?.etiquetaP" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IfX66E1LEfCIS7Qdd8ccrg" name="vendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IfX66U1LEfCIS7Qdd8ccrg" type="JAVA_METHOD" expression="setEtiquetaP">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9Wz_CzGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9Wz_DDGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9Wz_DTGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9Wz_DjGTEfCkYdaGFVhtZg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9Wz_DzGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_9Wz_EDGTEfCkYdaGFVhtZg">
            <targetForm xmi:type="expression:Expression" xmi:id="_TWOvsE1LEfCIS7Qdd8ccrg" name="newetiqueta" content="13679ef6-8d52-4fe6-92b9-24b994e4d91a" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_9Wz_EjGTEfCkYdaGFVhtZg">
            <inputs xmi:type="process:ContractInput" xmi:id="_IfX64E1LEfCIS7Qdd8ccrg" name="vendasInput" type="COMPLEX" dataReference="vendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_IfX64U1LEfCIS7Qdd8ccrg" name="etiquetaP" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9Wz_EzGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_SNvGYDGbEfC-4Z9zH4y95A" name="Produto para entrega" outgoing="_S6TRcDGbEfC-4Z9zH4y95A" event="Msg" incomingMessag="_LodmkDyTEfCJUObNuNZMMQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SNvtcTGbEfC-4Z9zH4y95A" name="Produto para entrega" content="Produto para entrega" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SNvtcDGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SNvtcjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wjFUMDGbEfC-4Z9zH4y95A" name="Acrescentar identificação do cliente" outgoing="_WIo1sDGbEfC-4Z9zH4y95A" incoming="_yBJVADGYEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yBIt8TGYEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yBIt8DGYEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yBIt8jGYEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_JAE0NE1LEfCIS7Qdd8ccrg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JAE0NU1LEfCIS7Qdd8ccrg" name="vendas" content="vendas" type="TYPE_VARIABLE" returnType="com.company.model.Vendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JAE0Nk1LEfCIS7Qdd8ccrg" name="vendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Vendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JAE0N01LEfCIS7Qdd8ccrg" name="vendasInput.etiquetaP" content="vendasInput?.etiquetaP" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JAE0OE1LEfCIS7Qdd8ccrg" name="vendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JAE0OU1LEfCIS7Qdd8ccrg" type="JAVA_METHOD" expression="setEtiquetaP">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yBIt8zGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yBIt9DGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yBIt9TGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yBIt9zGYEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yBIt9jGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wjF7STGbEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_kLZWAE1LEfCIS7Qdd8ccrg" name="newIdentificao" content="32dc8656-b7d9-48dd-817a-bd8e157d350c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wjF7SDGbEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_JAE0ME1LEfCIS7Qdd8ccrg" name="vendasInput" type="COMPLEX" dataReference="vendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_JAE0MU1LEfCIS7Qdd8ccrg" name="etiquetaP" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JAE0Mk1LEfCIS7Qdd8ccrg" name="identificacao" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JAE0M01LEfCIS7Qdd8ccrg" name="novaEtiquetaP" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wjF7SzGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_w3bzkDGbEfC-4Z9zH4y95A" name="Acrescentar uma nova etiqueta &quot;P&quot;" outgoing="_a5RTIDGbEfC-4Z9zH4y95A" incoming="_WIo1sDGbEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WIoOojGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WIoOoTGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WIoOozGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_KMAb0E1LEfCIS7Qdd8ccrg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KMAb0U1LEfCIS7Qdd8ccrg" name="vendas" content="vendas" type="TYPE_VARIABLE" returnType="com.company.model.Vendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KMAb0k1LEfCIS7Qdd8ccrg" name="vendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Vendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KMAb001LEfCIS7Qdd8ccrg" name="vendasInput.etiquetaP" content="vendasInput?.etiquetaP" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_KMAb1E1LEfCIS7Qdd8ccrg" name="vendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_KMAb1U1LEfCIS7Qdd8ccrg" type="JAVA_METHOD" expression="setEtiquetaP">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WIoOpDGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WIoOpTGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WIoOpjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WIoOqDGbEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WIoOpzGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_w3bzmjGbEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_ooOtsE1LEfCIS7Qdd8ccrg" name="newEtiquetaP" content="c46c6c86-02d6-4d2d-b4f1-609afed4cd3b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_w3bzmTGbEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_KL_0wE1LEfCIS7Qdd8ccrg" name="vendasInput" type="COMPLEX" dataReference="vendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_KL_0wU1LEfCIS7Qdd8ccrg" name="etiquetaP" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_KL_0wk1LEfCIS7Qdd8ccrg" name="identificacao" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_KL_0w01LEfCIS7Qdd8ccrg" name="novaEtiquetaP" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_w3bznDGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_VW8eEDyTEfCJUObNuNZMMQ" name="Produto pronto para venda" incoming="_a5RTIDGbEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_a5QsETGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_a5QsEDGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_a5QsEjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_FyT3sE1LEfCIS7Qdd8ccrg" name="vendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Vendas">
        <defaultValue xmi:type="expression:Expression" xmi:id="_FyT3sU1LEfCIS7Qdd8ccrg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_9Wz_FDGTEfCkYdaGFVhtZg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_2bhQcE3lEfCX2JYZsK0L_A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_9Wz_FjGTEfCkYdaGFVhtZg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_9Wz_FzGTEfCkYdaGFVhtZg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yBJVADGYEfC-4Z9zH4y95A" target="_wjFUMDGbEfC-4Z9zH4y95A" source="_9Wz_BzGTEfCkYdaGFVhtZg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yBJVATGYEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_yBJVAjGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S6TRcDGbEfC-4Z9zH4y95A" target="_9Wz_BzGTEfCkYdaGFVhtZg" source="_SNvGYDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S6TRcTGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_S6TRcjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WIo1sDGbEfC-4Z9zH4y95A" target="_w3bzkDGbEfC-4Z9zH4y95A" source="_wjFUMDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WIo1sTGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_WIo1sjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_a5RTIDGbEfC-4Z9zH4y95A" target="_VW8eEDyTEfCJUObNuNZMMQ" source="_w3bzkDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_a5RTITGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_a5RTIjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_9Wz_GzGTEfCkYdaGFVhtZg" documentation="This is an example of actor that is mapped to any ACME users" name="Técnico de área de operações"/>
      <contract xmi:type="process:Contract" xmi:id="_9Wz_HDGTEfCkYdaGFVhtZg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_HTGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_HjGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_HzGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_IDGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_ITGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_IjGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_IzGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_JDGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_JTGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_JjGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_JzGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_KDGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_KTGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_KjGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_KzGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_9Wz_LDGTEfCkYdaGFVhtZg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_9Wz_LTGTEfCkYdaGFVhtZg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_9Wz_LjGTEfCkYdaGFVhtZg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_9Wz_LzGTEfCkYdaGFVhtZg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_9Wz_MDGTEfCkYdaGFVhtZg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_9Wz_MTGTEfCkYdaGFVhtZg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_9Wz_MjGTEfCkYdaGFVhtZg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_9Wz_MzGTEfCkYdaGFVhtZg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_9Wz_NDGTEfCkYdaGFVhtZg" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_LodmkDyTEfCJUObNuNZMMQ" name="Msg" target="_SNvGYDGbEfC-4Z9zH4y95A" source="_DvaskDGkEfC-n5Sky3geQg"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_HeOUAE1YEfCIS7Qdd8ccrg" name="MsgArmazenamento" target="_GkLGkE1YEfCIS7Qdd8ccrg" source="_1klxoDyQEfCJUObNuNZMMQ"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_9Wz_NTGTEfCkYdaGFVhtZg" type="Process" element="_9Wz_ADGTEfCkYdaGFVhtZg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="__zTPsE1XEfCIS7Qdd8ccrg" type="2007" element="__vl0YE1XEfCIS7Qdd8ccrg">
      <children xmi:type="notation:DecorationNode" xmi:id="__zT2wE1XEfCIS7Qdd8ccrg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="__zT2wU1XEfCIS7Qdd8ccrg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_C1GMwE1YEfCIS7Qdd8ccrg" type="3007" element="_C1E-oE1YEfCIS7Qdd8ccrg">
          <children xmi:type="notation:DecorationNode" xmi:id="_C1Gz0E1YEfCIS7Qdd8ccrg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_C1Gz0U1YEfCIS7Qdd8ccrg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_GkLtoE1YEfCIS7Qdd8ccrg" type="3012" element="_GkLGkE1YEfCIS7Qdd8ccrg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GkMUsE1YEfCIS7Qdd8ccrg" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GkMUsU1YEfCIS7Qdd8ccrg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GkLtoU1YEfCIS7Qdd8ccrg" x="95" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_K0eeIE1YEfCIS7Qdd8ccrg" type="3003" element="_K0dQAE1YEfCIS7Qdd8ccrg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_K0fFME1YEfCIS7Qdd8ccrg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_K0fFMU1YEfCIS7Qdd8ccrg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K0eeIU1YEfCIS7Qdd8ccrg" x="1427" y="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NVAhPE1YEfCIS7Qdd8ccrg" type="3005" element="_NU_6IE1YEfCIS7Qdd8ccrg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NVAhPk1YEfCIS7Qdd8ccrg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NVAhPU1YEfCIS7Qdd8ccrg" x="346" y="77" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_N76wNU1YEfCIS7Qdd8ccrg" type="3005" element="_N76JIE1YEfCIS7Qdd8ccrg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_N76wN01YEfCIS7Qdd8ccrg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N76wNk1YEfCIS7Qdd8ccrg" x="662" y="78" width="156" height="78"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_C1GMwU1YEfCIS7Qdd8ccrg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_C1GMwk1YEfCIS7Qdd8ccrg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_C1GMw01YEfCIS7Qdd8ccrg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_C1Gz0k1YEfCIS7Qdd8ccrg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C1GMxE1YEfCIS7Qdd8ccrg" x="310" y="162"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="__zTPsU1XEfCIS7Qdd8ccrg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="__zTPsk1XEfCIS7Qdd8ccrg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="__zTPs01XEfCIS7Qdd8ccrg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="__zT2wk1XEfCIS7Qdd8ccrg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="__zTPtE1XEfCIS7Qdd8ccrg" width="1620" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_HdlhEDGcEfC-4Z9zH4y95A" type="2007" element="_Hdk6ADGcEfC-4Z9zH4y95A">
      <children xmi:type="notation:DecorationNode" xmi:id="_HdlhFTGcEfC-4Z9zH4y95A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_HdlhFjGcEfC-4Z9zH4y95A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_IDhfsDGcEfC-4Z9zH4y95A" type="3007" element="_IDg4oDGcEfC-4Z9zH4y95A">
          <children xmi:type="notation:DecorationNode" xmi:id="_IDhftTGcEfC-4Z9zH4y95A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IDhftjGcEfC-4Z9zH4y95A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_-dA-0DGjEfC-n5Sky3geQg" type="3008" element="_-dAXwDGjEfC-n5Sky3geQg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-dA-0jGjEfC-n5Sky3geQg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-dA-0zGjEfC-n5Sky3geQg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-dA-0TGjEfC-n5Sky3geQg" x="1022" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DvbTozGkEfC-n5Sky3geQg" type="3011" element="_DvaskDGkEfC-n5Sky3geQg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DvbTpTGkEfC-n5Sky3geQg" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DvbTpjGkEfC-n5Sky3geQg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DvbTpDGkEfC-n5Sky3geQg" x="1431" y="144"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1klxpDyQEfCJUObNuNZMMQ" type="3011" element="_1klxoDyQEfCJUObNuNZMMQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1kmYsDyQEfCJUObNuNZMMQ" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1kmYsTyQEfCJUObNuNZMMQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1klxpTyQEfCJUObNuNZMMQ" x="1432" y="22" width="28" height="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_j027HUIjEfCOhu7W5Z33XQ" type="3005" element="_j027EEIjEfCOhu7W5Z33XQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j027H0IjEfCOhu7W5Z33XQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j027HkIjEfCOhu7W5Z33XQ" x="696" y="49" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ETo7kEIZEfCOhu7W5Z33XQ" type="3005" element="_EToUgEIZEfCOhu7W5Z33XQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ETo7kkIZEfCOhu7W5Z33XQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ETo7kUIZEfCOhu7W5Z33XQ" x="995" y="192" width="154" height="77"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IDhfsTGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IDhfsjGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IDhfszGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IDhftzGcEfC-4Z9zH4y95A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IDhftDGcEfC-4Z9zH4y95A" x="53" y="10" width="1649" height="356"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_JCXGgTGcEfC-4Z9zH4y95A" type="3007" element="_JCXGgDGcEfC-4Z9zH4y95A">
          <children xmi:type="notation:DecorationNode" xmi:id="_JCXGhjGcEfC-4Z9zH4y95A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_JCXtkDGcEfC-4Z9zH4y95A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_21aYdDGcEfC-4Z9zH4y95A" type="3002" element="_21aYcDGcEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_21a_gDGcEfC-4Z9zH4y95A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_21a_gTGcEfC-4Z9zH4y95A" x="-1" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_21aYdTGcEfC-4Z9zH4y95A" x="103" y="188"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5vZdUDGcEfC-4Z9zH4y95A" type="3009" element="_5vY2QDGcEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5vZdUjGcEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5vZdUzGcEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5vZdUTGcEfC-4Z9zH4y95A" x="230" y="178"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IN0OvTGdEfC-4Z9zH4y95A" type="3005" element="_IN0OsDGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IN0OvzGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IN0OvjGdEfC-4Z9zH4y95A" x="350" y="59" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RAuOzTGdEfC-4Z9zH4y95A" type="3005" element="_RAuOwDGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RAuOzzGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAuOzjGdEfC-4Z9zH4y95A" x="349" y="162" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RfbkADGdEfC-4Z9zH4y95A" type="3005" element="_Rfa88DGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RfbkAjGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfbkATGdEfC-4Z9zH4y95A" x="349" y="256" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UaHzhDGdEfC-4Z9zH4y95A" type="3009" element="_UaHzgDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UaHzhjGdEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UaHzhzGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UaHzhTGdEfC-4Z9zH4y95A" x="590" y="178"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ajKOVDGdEfC-4Z9zH4y95A" type="3008" element="_ajKOUDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ajK1YDGdEfC-4Z9zH4y95A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ajK1YTGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ajKOVTGdEfC-4Z9zH4y95A" x="758" y="178"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cAK-4DGdEfC-4Z9zH4y95A" type="3009" element="_cAKX0DGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_cAK-4jGdEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_cAK-4zGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cAK-4TGdEfC-4Z9zH4y95A" x="905" y="178"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eUsmQjGdEfC-4Z9zH4y95A" type="3009" element="_eUr_MDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eUsmRDGdEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eUsmRTGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eUsmQzGdEfC-4Z9zH4y95A" x="1205" y="178"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fbLGJDGdEfC-4Z9zH4y95A" type="3003" element="_fbLGIDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fbLtMDGdEfC-4Z9zH4y95A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fbLtMTGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fbLGJTGdEfC-4Z9zH4y95A" x="1429" y="185"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o7qk_TGdEfC-4Z9zH4y95A" type="3005" element="_o7qk8DGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_o7rMADGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o7qk_jGdEfC-4Z9zH4y95A" x="996" y="268" width="158" height="79"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_JCXGgjGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_JCXGgzGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_JCXGhDGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_JCXtkTGcEfC-4Z9zH4y95A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JCXGhTGcEfC-4Z9zH4y95A" x="53" y="272" width="1649" height="421"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_HdlhETGcEfC-4Z9zH4y95A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_HdlhEjGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_HdlhEzGcEfC-4Z9zH4y95A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_HdlhFzGcEfC-4Z9zH4y95A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HdlhFDGcEfC-4Z9zH4y95A" width="1677" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_9Wz_NjGTEfCkYdaGFVhtZg" type="2007" element="_9Wz_ATGTEfCkYdaGFVhtZg">
      <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_NzGTEfCkYdaGFVhtZg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_ODGTEfCkYdaGFVhtZg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_9Wz_OTGTEfCkYdaGFVhtZg" type="3007" element="_9Wz_AjGTEfCkYdaGFVhtZg">
          <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_OjGTEfCkYdaGFVhtZg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_OzGTEfCkYdaGFVhtZg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_9Wz_PDGTEfCkYdaGFVhtZg" type="3005" element="_9Wz_BzGTEfCkYdaGFVhtZg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_PTGTEfCkYdaGFVhtZg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Wz_PjGTEfCkYdaGFVhtZg" x="347" y="87" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SNvtczGbEfC-4Z9zH4y95A" type="3012" element="_SNvGYDGbEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SNwUgDGbEfC-4Z9zH4y95A" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SNwUgTGbEfC-4Z9zH4y95A" y="14"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SNvtdDGbEfC-4Z9zH4y95A" x="95" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wjF7TDGbEfC-4Z9zH4y95A" type="3005" element="_wjFUMDGbEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wjGiUDGbEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wjF7TTGbEfC-4Z9zH4y95A" x="662" y="85" width="154" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w3bznTGbEfC-4Z9zH4y95A" type="3005" element="_w3bzkDGbEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_w3bznzGbEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w3bznjGbEfC-4Z9zH4y95A" x="1002" y="85" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VW9FITyTEfCJUObNuNZMMQ" type="3003" element="_VW8eEDyTEfCJUObNuNZMMQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VW9FIzyTEfCJUObNuNZMMQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VW9FJDyTEfCJUObNuNZMMQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VW9FIjyTEfCJUObNuNZMMQ" x="1428" y="108" width="28" height="28"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_9Wz_QzGTEfCkYdaGFVhtZg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_9Wz_RDGTEfCkYdaGFVhtZg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_9Wz_RTGTEfCkYdaGFVhtZg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_9Wz_RjGTEfCkYdaGFVhtZg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Wz_RzGTEfCkYdaGFVhtZg"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_9Wz_SDGTEfCkYdaGFVhtZg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_9Wz_STGTEfCkYdaGFVhtZg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_9Wz_SjGTEfCkYdaGFVhtZg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_9Wz_SzGTEfCkYdaGFVhtZg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Wz_TDGTEfCkYdaGFVhtZg" width="1620" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_9Wz_TTGTEfCkYdaGFVhtZg"/>
    <edges xmi:type="notation:Connector" xmi:id="_yBJVAzGYEfC-4Z9zH4y95A" type="4001" element="_yBJVADGYEfC-4Z9zH4y95A" source="_9Wz_PDGTEfCkYdaGFVhtZg" target="_wjF7TDGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yBJVBjGYEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yBJVBzGYEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yBJVBDGYEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yBJVBTGYEfC-4Z9zH4y95A" points="[60, -2, -194, 3]$[194, -2, -60, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S6TRczGbEfC-4Z9zH4y95A" type="4001" element="_S6TRcDGbEfC-4Z9zH4y95A" source="_SNvtczGbEfC-4Z9zH4y95A" target="_9Wz_PDGTEfCkYdaGFVhtZg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S6T4gDGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S6T4gTGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S6TRdDGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S6TRdTGbEfC-4Z9zH4y95A" points="[-1, -15, -99, -14]$[90, -15, -8, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S6VGoDGbEfC-4Z9zH4y95A" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S6VGoTGbEfC-4Z9zH4y95A" id="(0.07,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WIo1szGbEfC-4Z9zH4y95A" type="4001" element="_WIo1sDGbEfC-4Z9zH4y95A" source="_wjF7TDGbEfC-4Z9zH4y95A" target="_w3bznTGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WIo1tjGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WIo1tzGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WIo1tDGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WIo1tTGbEfC-4Z9zH4y95A" points="[60, -2, -161, -2]$[161, -2, -60, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_a5RTIzGbEfC-4Z9zH4y95A" type="4001" element="_a5RTIDGbEfC-4Z9zH4y95A" source="_w3bznTGbEfC-4Z9zH4y95A" target="_VW9FITyTEfCJUObNuNZMMQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_a5RTJjGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_a5RTJzGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_a5RTJDGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_a5RTJTGbEfC-4Z9zH4y95A" points="[60, -3, -166, 2]$[211, -3, -15, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6p0eMDGcEfC-4Z9zH4y95A" type="4001" element="_6pz3IDGcEfC-4Z9zH4y95A" source="_21aYdDGcEfC-4Z9zH4y95A" target="_5vZdUDGcEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6p0eMzGcEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6p0eNDGcEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6p0eMTGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6p0eMjGcEfC-4Z9zH4y95A" points="[-2, -6, -140, 5]$[142, 7, 4, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6p1sUDGcEfC-4Z9zH4y95A" id="(1.0,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BdZq0DGdEfC-4Z9zH4y95A" type="4001" element="_BdZDwDGdEfC-4Z9zH4y95A" source="_5vZdUDGcEfC-4Z9zH4y95A" target="_IN0OvTGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BdZq0zGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BdZq1DGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BdZq0TGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BdZq0jGdEfC-4Z9zH4y95A" points="[-20, -17, -110, 87]$[-20, -102, -110, 2]$[80, -102, -10, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BdaR4DGdEfC-4Z9zH4y95A" id="(0.9302325581395349,0.4186046511627907)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BdaR4TGdEfC-4Z9zH4y95A" id="(0.07,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CWgdEzGdEfC-4Z9zH4y95A" type="4001" element="_CWgdEDGdEfC-4Z9zH4y95A" source="_5vZdUDGcEfC-4Z9zH4y95A" target="_RAuOzTGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CWgdFjGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CWhEIDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CWgdFDGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CWgdFTGdEfC-4Z9zH4y95A" points="[-2, -4, -102, 0]$[79, -4, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CWhrMDGdEfC-4Z9zH4y95A" id="(0.7674418604651163,0.3953488372093023)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CWhrMTGdEfC-4Z9zH4y95A" id="(0.21,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CxmdoDGdEfC-4Z9zH4y95A" type="4001" element="_Cxl2kDGdEfC-4Z9zH4y95A" source="_5vZdUDGcEfC-4Z9zH4y95A" target="_RfbkADGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CxmdozGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CxmdpDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CxmdoTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CxmdojGdEfC-4Z9zH4y95A" points="[-23, 13, -123, -84]$[-23, 87, -123, -10]$[76, 87, -24, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CxnEsDGdEfC-4Z9zH4y95A" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CxnEsTGdEfC-4Z9zH4y95A" id="(0.16,0.62)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VBbEEDGdEfC-4Z9zH4y95A" type="4001" element="_VBadADGdEfC-4Z9zH4y95A" source="_RAuOzTGdEfC-4Z9zH4y95A" target="_UaHzhDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VBbEEzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VBbEFDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VBbEETGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VBbEEjGdEfC-4Z9zH4y95A" points="[0, 0, -137, -28]$[127, 27, -10, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VBbrIDGdEfC-4Z9zH4y95A" id="(1.0,0.4166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VBbrITGdEfC-4Z9zH4y95A" id="(0.23255813953488372,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V0Ny8zGdEfC-4Z9zH4y95A" type="4001" element="_V0Ny8DGdEfC-4Z9zH4y95A" source="_IN0OvTGdEfC-4Z9zH4y95A" target="_UaHzhDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V0Ny9jGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V0Ny9zGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V0Ny9DGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V0Ny9TGdEfC-4Z9zH4y95A" points="[0, 6, -108, -105]$[107, 6, -1, -105]$[107, 91, -1, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_V0PBEDGdEfC-4Z9zH4y95A" id="(1.0,0.38571428571428573)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WfPs8zGdEfC-4Z9zH4y95A" type="4001" element="_WfPs8DGdEfC-4Z9zH4y95A" source="_RfbkADGdEfC-4Z9zH4y95A" target="_UaHzhDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WfPs9jGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WfPs9zGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WfPs9DGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WfPs9TGdEfC-4Z9zH4y95A" points="[0, 3, -170, 94]$[168, 3, -2, 94]$[168, -72, -2, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WfQUADGdEfC-4Z9zH4y95A" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lDfZgDGdEfC-4Z9zH4y95A" type="4001" element="_lDeycDGdEfC-4Z9zH4y95A" source="_UaHzhDGdEfC-4Z9zH4y95A" target="_ajKOVDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lDfZgzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lDfZhDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lDfZgTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lDfZgjGdEfC-4Z9zH4y95A" points="[0, 1, -64, -1]$[65, 1, 1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lDgAkDGdEfC-4Z9zH4y95A" id="(0.9534883720930233,0.4418604651162791)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jMlAYExmEfCNq_Z_7Oph1Q" id="(0.0,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_laAcEDGdEfC-4Z9zH4y95A" type="4001" element="_lZ_N8DGdEfC-4Z9zH4y95A" source="_ajKOVDGdEfC-4Z9zH4y95A" target="_cAK-4DGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_laAcEzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_laAcFDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_laAcETGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_laAcEjGdEfC-4Z9zH4y95A" points="[-2, -8, -127, -1]$[105, -8, -20, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_laBDIDGdEfC-4Z9zH4y95A" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lvjOQDGdEfC-4Z9zH4y95A" type="4001" element="_lvinMDGdEfC-4Z9zH4y95A" source="_cAK-4DGdEfC-4Z9zH4y95A" target="_ETo7kEIZEfCOhu7W5Z33XQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lvjOQzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lvj1UDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lvjOQTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lvjOQjGdEfC-4Z9zH4y95A" points="[-2, 1, -87, 335]$[-2, -319, -87, 15]$[72, -319, -13, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lvkcYDGdEfC-4Z9zH4y95A" id="(0.4883720930232558,0.023255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lvkcYTGdEfC-4Z9zH4y95A" id="(0.09,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mGqtwDGdEfC-4Z9zH4y95A" type="4001" element="_mGqGsDGdEfC-4Z9zH4y95A" source="_cAK-4DGdEfC-4Z9zH4y95A" target="_o7qk_TGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mGqtwzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mGqtxDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mGqtwTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mGqtwjGdEfC-4Z9zH4y95A" points="[-22, 20, -93, -52]$[-22, 80, -93, 8]$[43, 80, -28, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mGrU0DGdEfC-4Z9zH4y95A" id="(1.0,0.5348837209302325)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mGrU0TGdEfC-4Z9zH4y95A" id="(0.2,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_meDTADGdEfC-4Z9zH4y95A" type="4001" element="_meCr8DGdEfC-4Z9zH4y95A" source="_o7qk_TGdEfC-4Z9zH4y95A" target="_eUsmQjGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_meDTAzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_meDTBDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_meDTATGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_meDTAjGdEfC-4Z9zH4y95A" points="[0, -17, -72, 94]$[70, -17, -2, 94]$[70, -92, -2, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_meD6EDGdEfC-4Z9zH4y95A" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_m694gzGdEfC-4Z9zH4y95A" type="4001" element="_m694gDGdEfC-4Z9zH4y95A" source="_ETo7kEIZEfCOhu7W5Z33XQ" target="_eUsmQjGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_m694hjGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_m694hzGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_m694hDGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_m694hTGdEfC-4Z9zH4y95A" points="[0, -3, -95, -323]$[65, -3, -30, -323]$[65, 314, -30, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_m6-fkDGdEfC-4Z9zH4y95A" id="(1.0,0.52)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_d2v9oEyGEfCNq_Z_7Oph1Q" id="(0.4418604651162791,0.18604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nYStsDGdEfC-4Z9zH4y95A" type="4001" element="_nYSGoDGdEfC-4Z9zH4y95A" source="_eUsmQjGdEfC-4Z9zH4y95A" target="_fbLGJDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nYStszGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nYSttDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nYStsTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nYStsjGdEfC-4Z9zH4y95A" points="[-14, 6, -186, 0]$[157, 6, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nYTUwDGdEfC-4Z9zH4y95A" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__V02IDGjEfC-n5Sky3geQg" type="4001" element="__VzoADGjEfC-n5Sky3geQg" source="_ajKOVDGdEfC-4Z9zH4y95A" target="_j027HUIjEfCOhu7W5Z33XQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__V02IzGjEfC-n5Sky3geQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__V02JDGjEfC-n5Sky3geQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__V02ITGjEfC-n5Sky3geQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__V02IjGjEfC-n5Sky3geQg" points="[-1, -20, 4, 447]$[-1, -428, 4, 39]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_C5oUFTGkEfC-n5Sky3geQg" type="4001" element="_C5oUEjGkEfC-n5Sky3geQg" source="_-dA-0DGjEfC-n5Sky3geQg" target="_1klxpDyQEfCJUObNuNZMMQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_C5oUGDGkEfC-n5Sky3geQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_C5oUGTGkEfC-n5Sky3geQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_C5oUFjGkEfC-n5Sky3geQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_C5oUFzGkEfC-n5Sky3geQg" points="[0, -21, -403, 30]$[0, -53, -403, -2]$[389, -53, -14, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Dvb6sDGkEfC-n5Sky3geQg" type="4001" element="_DvbTpzGkEfC-n5Sky3geQg" source="_-dA-0DGjEfC-n5Sky3geQg" target="_DvbTozGkEfC-n5Sky3geQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Dvb6szGkEfC-n5Sky3geQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Dvb6tDGkEfC-n5Sky3geQg" y="-20"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Dvb6sTGkEfC-n5Sky3geQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Dvb6sjGkEfC-n5Sky3geQg" points="[0, 22, -403, -50]$[0, 70, -403, -2]$[388, 70, -15, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LoeNoDyTEfCJUObNuNZMMQ" type="4002" element="_LodmkDyTEfCJUObNuNZMMQ" source="_DvbTozGkEfC-n5Sky3geQg" target="_SNvtczGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LoeNozyTEfCJUObNuNZMMQ" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LoeNpDyTEfCJUObNuNZMMQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LoeNoTyTEfCJUObNuNZMMQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LoeNojyTEfCJUObNuNZMMQ" points="[14, 2, 1365, -772]$[469, 2, 1820, -772]$[469, 639, 1820, -135]$[-1398, 639, -47, -135]$[-1398, 753, -47, -21]$[-1348, 753, 3, -21]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7VSCcE3qEfCX2JYZsK0L_A" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_II6HgkIaEfCOhu7W5Z33XQ" type="4001" element="_II5gcEIaEfCOhu7W5Z33XQ" source="_j027HUIjEfCOhu7W5Z33XQ" target="_-dA-0DGjEfC-n5Sky3geQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_II6ukEIaEfCOhu7W5Z33XQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_II6ukUIaEfCOhu7W5Z33XQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_II6Hg0IaEfCOhu7W5Z33XQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_II6HhEIaEfCOhu7W5Z33XQ" points="[0, 3, -56, 0]$[53, 3, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_II7VoEIaEfCOhu7W5Z33XQ" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_II7VoUIaEfCOhu7W5Z33XQ" id="(0.09302325581395349,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HePiIE1YEfCIS7Qdd8ccrg" type="4002" element="_HeOUAE1YEfCIS7Qdd8ccrg" source="_1klxpDyQEfCJUObNuNZMMQ" target="_GkLtoE1YEfCIS7Qdd8ccrg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HePiI01YEfCIS7Qdd8ccrg" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HePiJE1YEfCIS7Qdd8ccrg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HePiIU1YEfCIS7Qdd8ccrg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HePiIk1YEfCIS7Qdd8ccrg" points="[-1, 18, 1360, -1156]$[518, 18, 1879, -1156]$[518, 1034, 1879, -140]$[-1422, 1034, -61, -140]$[-1422, 1170, -61, -4]$[-1365, 1170, -4, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HeRXUE1YEfCIS7Qdd8ccrg" id="(1.0,0.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HeRXUU1YEfCIS7Qdd8ccrg" id="(0.13333333333333333,0.6333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JeuMI01YEfCIS7Qdd8ccrg" type="4001" element="_JeuMIE1YEfCIS7Qdd8ccrg" source="_GkLtoE1YEfCIS7Qdd8ccrg" target="_NVAhPE1YEfCIS7Qdd8ccrg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JeuMJk1YEfCIS7Qdd8ccrg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JeuMJ01YEfCIS7Qdd8ccrg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JeuMJE1YEfCIS7Qdd8ccrg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JeuMJU1YEfCIS7Qdd8ccrg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KBuylk1YEfCIS7Qdd8ccrg" type="4001" element="_KBuyk01YEfCIS7Qdd8ccrg" source="_NVAhPE1YEfCIS7Qdd8ccrg" target="_N76wNU1YEfCIS7Qdd8ccrg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KBvZoE1YEfCIS7Qdd8ccrg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KBvZoU1YEfCIS7Qdd8ccrg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KBuyl01YEfCIS7Qdd8ccrg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KBuymE1YEfCIS7Qdd8ccrg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K0fsQ01YEfCIS7Qdd8ccrg" type="4001" element="_K0fsQE1YEfCIS7Qdd8ccrg" source="_N76wNU1YEfCIS7Qdd8ccrg" target="_K0eeIE1YEfCIS7Qdd8ccrg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K0fsRk1YEfCIS7Qdd8ccrg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K0fsR01YEfCIS7Qdd8ccrg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K0fsRE1YEfCIS7Qdd8ccrg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K0fsRU1YEfCIS7Qdd8ccrg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
