<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:parameter="http://www.bonitasoft.org/ns/bpm/parameter" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_9Wz_ADGTEfCkYdaGFVhtZg" name="MyDiagram" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_9Wz_ATGTEfCkYdaGFVhtZg" name="Venda de produto">
      <elements xmi:type="process:Lane" xmi:id="_9Wz_AjGTEfCkYdaGFVhtZg" name="Employee lane" actor="_9Wz_GzGTEfCkYdaGFVhtZg">
        <elements xmi:type="process:Task" xmi:id="_9Wz_BzGTEfCkYdaGFVhtZg" name="Atribuir etiqueta &quot;P&quot;" outgoing="_yBJVADGYEfC-4Z9zH4y95A" incoming="_S6TRcDGbEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9Wz_CDGTEfCkYdaGFVhtZg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9Wz_CTGTEfCkYdaGFVhtZg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9Wz_CjGTEfCkYdaGFVhtZg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9Wz_CzGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9Wz_DDGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9Wz_DTGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9Wz_DjGTEfCkYdaGFVhtZg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9Wz_DzGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_9Wz_EDGTEfCkYdaGFVhtZg">
            <targetForm xmi:type="expression:Expression" xmi:id="_H2h9EEIlEfCOhu7W5Z33XQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_9Wz_EjGTEfCkYdaGFVhtZg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9Wz_EzGTEfCkYdaGFVhtZg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_SNvGYDGbEfC-4Z9zH4y95A" name="Produto para entrega" outgoing="_S6TRcDGbEfC-4Z9zH4y95A" event="Msg" incomingMessag="_LodmkDyTEfCJUObNuNZMMQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SNvtcTGbEfC-4Z9zH4y95A" name="Produto para entrega" content="Produto para entrega" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SNvtcDGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SNvtcjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wjFUMDGbEfC-4Z9zH4y95A" name="Acrescentar identificação do cliente" outgoing="_WIo1sDGbEfC-4Z9zH4y95A" incoming="_yBJVADGYEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yBIt8TGYEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yBIt8DGYEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yBIt8jGYEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yBIt8zGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yBIt9DGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yBIt9TGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yBIt9zGYEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yBIt9jGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wjF7STGbEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_H2h9EUIlEfCOhu7W5Z33XQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wjF7SDGbEfC-4Z9zH4y95A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wjF7SzGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_w3bzkDGbEfC-4Z9zH4y95A" name="Acrescentar uma nova etiqueta &quot;P&quot;" outgoing="_a5RTIDGbEfC-4Z9zH4y95A" incoming="_WIo1sDGbEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WIoOojGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WIoOoTGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WIoOozGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WIoOpDGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WIoOpTGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WIoOpjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WIoOqDGbEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WIoOpzGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_w3bzmjGbEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_H2h9EkIlEfCOhu7W5Z33XQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_w3bzmTGbEfC-4Z9zH4y95A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_w3bznDGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_VW8eEDyTEfCJUObNuNZMMQ" name="Produto pronto para venda ao cliente" incoming="_a5RTIDGbEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_a5QsETGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_a5QsEDGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_a5QsEjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_9Wz_FDGTEfCkYdaGFVhtZg">
        <targetForm xmi:type="expression:Expression" xmi:id="_H2h9E0IlEfCOhu7W5Z33XQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_9Wz_FjGTEfCkYdaGFVhtZg">
        <targetForm xmi:type="expression:Expression" xmi:id="_9Wz_FzGTEfCkYdaGFVhtZg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yBJVADGYEfC-4Z9zH4y95A" target="_wjFUMDGbEfC-4Z9zH4y95A" source="_9Wz_BzGTEfCkYdaGFVhtZg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yBJVATGYEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_yBJVAjGYEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S6TRcDGbEfC-4Z9zH4y95A" target="_9Wz_BzGTEfCkYdaGFVhtZg" source="_SNvGYDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S6TRcTGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_S6TRcjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WIo1sDGbEfC-4Z9zH4y95A" target="_w3bzkDGbEfC-4Z9zH4y95A" source="_wjFUMDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WIo1sTGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_WIo1sjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_a5RTIDGbEfC-4Z9zH4y95A" target="_VW8eEDyTEfCJUObNuNZMMQ" source="_w3bzkDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_a5RTITGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_a5RTIjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_9Wz_GzGTEfCkYdaGFVhtZg" documentation="This is an example of actor that is mapped to any ACME users" name="Técnico de área de operações"/>
      <contract xmi:type="process:Contract" xmi:id="_9Wz_HDGTEfCkYdaGFVhtZg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_HTGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_HjGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_HzGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_IDGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_ITGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_IjGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_IzGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_JDGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_JTGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_JjGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_JzGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_KDGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_9Wz_KTGTEfCkYdaGFVhtZg">
        <name xmi:type="expression:Expression" xmi:id="_9Wz_KjGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_9Wz_KzGTEfCkYdaGFVhtZg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_eu12gDGbEfC-4Z9zH4y95A" name="Armazenamento de produto">
      <elements xmi:type="process:Task" xmi:id="_wLCAkDGbEfC-4Z9zH4y95A" name="Atribuir etiqueta &quot;S&quot;" outgoing="_0oRA7DGbEfC-4Z9zH4y95A" incoming="_ul5OwTGbEfC-4Z9zH4y95A" actor="_pV0cQDGbEfC-4Z9zH4y95A">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ul4nsjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ul4nsTGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ul4nszGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_tWcVYjyZEfCfw76yGlE_oQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_tWcVYzyZEfCfw76yGlE_oQ" name="armazenamento" content="armazenamento" type="TYPE_VARIABLE" returnType="com.company.model.Armazenamento">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tWcVZDyZEfCfw76yGlE_oQ" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_tWcVZTyZEfCfw76yGlE_oQ" name="armazenamentoInput.id_produto" content="armazenamentoInput?.id_produto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_tWcVZjyZEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_tWcVZzyZEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setId_produto">
            <inputTypes>java.lang.Integer</inputTypes>
          </operator>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_uZ6kkDyZEfCfw76yGlE_oQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_uZ6kkTyZEfCfw76yGlE_oQ" name="armazenamento" content="armazenamento" type="TYPE_VARIABLE" returnType="com.company.model.Armazenamento">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uZ6kkjyZEfCfw76yGlE_oQ" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_uZ6kkzyZEfCfw76yGlE_oQ" name="armazenamentoInput1.id_produto" content="     ?.id_produto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer"/>
          <operator xmi:type="expression:Operator" xmi:id="_uZ6klTyZEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setId_produto">
            <inputTypes>java.lang.Integer</inputTypes>
          </operator>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ul4ntDGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ul4ntTGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ul4ntjGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ul4nuDGbEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ul4ntzGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_wLCAmjGbEfC-4Z9zH4y95A">
          <targetForm xmi:type="expression:Expression" xmi:id="_4nDuADyZEfCfw76yGlE_oQ" name="EtiquetaForm" content="5e63e90d-cd8a-4395-99b1-63b07ce3566c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_wLCAmTGbEfC-4Z9zH4y95A">
          <inputs xmi:type="process:ContractInput" xmi:id="_tWcVYDyZEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_tWcVYTyZEfCfw76yGlE_oQ" name="id_produto" type="INTEGER" createMode="false"/>
          </inputs>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_wLCnoDGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_1d0v4DGbEfC-4Z9zH4y95A" name="Armazenar em stock" outgoing="_5jJmgDGbEfC-4Z9zH4y95A" incoming="_0oRA7DGbEfC-4Z9zH4y95A" actor="_pV0cQDGbEfC-4Z9zH4y95A">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_0oRA4jGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_0oRA4TGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_0oRA4zGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_0oRA5DGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_0oRA5TGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0oRA5jGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_0oRA6DGbEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_0oRA5zGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_1d0v6jGbEfC-4Z9zH4y95A">
          <targetForm xmi:type="expression:Expression" xmi:id="_L_IV8DyaEfCfw76yGlE_oQ" name="ArmazenarForm" content="6258f882-71fc-40aa-a65b-80600bc9a28f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_1d0v6TGbEfC-4Z9zH4y95A">
          <inputs xmi:type="process:ContractInput" xmi:id="_xKq08DyZEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_xKq08TyZEfCfw76yGlE_oQ" name="id_produto" type="INTEGER" createMode="false"/>
          </inputs>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_1d0v7DGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_3SaS8DGbEfC-4Z9zH4y95A" name="outro teste" incoming="_5jJmgDGbEfC-4Z9zH4y95A">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_3Sa6ATGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_3Sa6ADGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_3Sa6AjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_r9An0DyaEfCfw76yGlE_oQ" name="Produto para armazenamento" outgoing="_ul5OwTGbEfC-4Z9zH4y95A">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_s2FeAjGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_s2FeATGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_s2FeAzGbEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_M8K34DyYEfCfw76yGlE_oQ" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento">
        <defaultValue xmi:type="expression:Expression" xmi:id="_M8K34TyYEfCfw76yGlE_oQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_eu12kDGbEfC-4Z9zH4y95A">
        <targetForm xmi:type="expression:Expression" xmi:id="_H1LSMEIlEfCOhu7W5Z33XQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_eu2dkDGbEfC-4Z9zH4y95A">
        <targetForm xmi:type="expression:Expression" xmi:id="_eu2dkTGbEfC-4Z9zH4y95A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ul5OwTGbEfC-4Z9zH4y95A" target="_wLCAkDGbEfC-4Z9zH4y95A" source="_r9An0DyaEfCfw76yGlE_oQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ul5OwjGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ul5OwzGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0oRA7DGbEfC-4Z9zH4y95A" target="_1d0v4DGbEfC-4Z9zH4y95A" source="_wLCAkDGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0oRn8DGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_0oRn8TGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5jJmgDGbEfC-4Z9zH4y95A" target="_3SaS8DGbEfC-4Z9zH4y95A" source="_1d0v4DGbEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5jKNkDGbEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_5jKNkTGbEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_pV0cQDGbEfC-4Z9zH4y95A" name="Técnico de área de operações"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_IjMFcDyYEfCfw76yGlE_oQ" name="dadad" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_eu2dkjGbEfC-4Z9zH4y95A">
        <inputs xmi:type="process:ContractInput" xmi:id="_obCyYDyZEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento">
          <inputs xmi:type="process:ContractInput" xmi:id="_obDZcDyZEfCfw76yGlE_oQ" name="id_produto" type="INTEGER"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eu12gTGbEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_eu12gjGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eu12gzGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eu12hDGbEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_eu12hTGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eu12hjGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eu12hzGbEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_eu12iDGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eu12iTGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eu12ijGbEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_eu12izGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eu12jDGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eu12jTGbEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_eu12jjGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eu12jzGbEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_Hdk6ADGcEfC-4Z9zH4y95A" name="Verificação dos produtos recebidos">
      <elements xmi:type="process:Lane" xmi:id="_IDg4oDGcEfC-4Z9zH4y95A" name="Técnico de área de operações" actor="_2XLAcDGgEfCnSJk-yp4Knw">
        <elements xmi:type="process:XORGateway" xmi:id="_-dAXwDGjEfC-n5Sky3geQg" name="Cliente ou stock" outgoing="_C5oUEjGkEfC-n5Sky3geQg _DvbTpzGkEfC-n5Sky3geQg" incoming="_II5gcEIaEfCOhu7W5Z33XQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-dAXwjGjEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-dAXwTGjEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-dAXwzGjEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_DvaskDGkEfC-n5Sky3geQg" name="Produto para entrega" incoming="_DvbTpzGkEfC-n5Sky3geQg" outgoingMessages="_LodmkDyTEfCJUObNuNZMMQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DvbToTGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DvbToDGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DvbTojGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_Loc_gDyTEfCJUObNuNZMMQ" name="Msg">
            <correlation xmi:type="process:Correlation" xmi:id="_Loc_gTyTEfCJUObNuNZMMQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_Loc_gjyTEfCJUObNuNZMMQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_Loc_gzyTEfCJUObNuNZMMQ" name="Venda de produto" content="Venda de produto" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_Loc_hDyTEfCJUObNuNZMMQ" name="Produto para entrega" content="Produto para entrega" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_Loc_hTyTEfCJUObNuNZMMQ"/>
          </events>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_1klxoDyQEfCJUObNuNZMMQ" name="Produto para armazenamento" incoming="_C5oUEjGkEfC-n5Sky3geQg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C5ntAjGkEfC-n5Sky3geQg" name="ProdutoArmazenamento" content="ProdutoArmazenamento" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C5ntATGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C5ntAzGkEfC-n5Sky3geQg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_Sy6bEDyTEfCJUObNuNZMMQ" name="MsgArmazenamento">
            <correlation xmi:type="process:Correlation" xmi:id="_Sy6bETyTEfCJUObNuNZMMQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_Sy6bEjyTEfCJUObNuNZMMQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_jD_YsTyaEfCfw76yGlE_oQ" name="Armazenamento de produto" content="Armazenamento de produto"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_jD_YsDyaEfCfw76yGlE_oQ" name="Produto para armazenamento" content="Produto para armazenamento"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_Sy6bFTyTEfCJUObNuNZMMQ"/>
          </events>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_EToUgEIZEfCOhu7W5Z33XQ" name="Devolver produtos e documentos" outgoing="_m694gDGdEfC-4Z9zH4y95A" incoming="_lvinMDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dY4eQTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dY4eQDGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dY4eQjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dY4eQzGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dY4eRDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dY4eRTGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dY4eRzGdEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dY4eRjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EToUikIZEfCOhu7W5Z33XQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_xslEYEIZEfCOhu7W5Z33XQ" name="DevolverProdutos" content="06d6c0bc-3213-48f9-859e-03b3f62f146f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EToUiUIZEfCOhu7W5Z33XQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EToUjEIZEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_j027EEIjEfCOhu7W5Z33XQ" name="Escolher se produto vai para cliente ou stock" outgoing="_II5gcEIaEfCOhu7W5Z33XQ" incoming="__VzoADGjEfC-n5Sky3geQg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FAygAUIaEfCOhu7W5Z33XQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FAygAkIaEfCOhu7W5Z33XQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FAygA0IaEfCOhu7W5Z33XQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_V4jR4kIbEfCOhu7W5Z33XQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_V4jR40IbEfCOhu7W5Z33XQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_V4jR5EIbEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_V4jR5UIbEfCOhu7W5Z33XQ" name="encomendasInput.destino" content="encomendasInput?.destino" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_V4jR50IbEfCOhu7W5Z33XQ" type="JAVA_METHOD" expression="setDestino">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3EtlsEIkEfCOhu7W5Z33XQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3EtlsUIkEfCOhu7W5Z33XQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3EtlskIkEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Etls0IkEfCOhu7W5Z33XQ" name="encomendasInput.destino" content="encomendasInput?.destino" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3EtltEIkEfCOhu7W5Z33XQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3EtltUIkEfCOhu7W5Z33XQ" type="JAVA_METHOD" expression="setDestino">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4AkxBUIkEfCOhu7W5Z33XQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4AkxBkIkEfCOhu7W5Z33XQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4AkxB0IkEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4AkxCEIkEfCOhu7W5Z33XQ" name="encomendasInput1.concordancia" content="     ?.concordancia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_4AkxCkIkEfCOhu7W5Z33XQ" type="JAVA_METHOD" expression="setConcordancia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4AkxC0IkEfCOhu7W5Z33XQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4AkxDEIkEfCOhu7W5Z33XQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4AkxDUIkEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4AkxDkIkEfCOhu7W5Z33XQ" name="encomendasInput1.aparencia" content="     ?.aparencia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_4AkxEEIkEfCOhu7W5Z33XQ" type="JAVA_METHOD" expression="setAparencia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4AkxEUIkEfCOhu7W5Z33XQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4AkxEkIkEfCOhu7W5Z33XQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4AkxE0IkEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4AkxFEIkEfCOhu7W5Z33XQ" name="encomendasInput1.quantidade" content="     ?.quantidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_4AkxFkIkEfCOhu7W5Z33XQ" type="JAVA_METHOD" expression="setQuantidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4AkxF0IkEfCOhu7W5Z33XQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4AkxGEIkEfCOhu7W5Z33XQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4AkxGUIkEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4AkxGkIkEfCOhu7W5Z33XQ" name="encomendasInput1.destino" content="     ?.destino" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_4AkxHEIkEfCOhu7W5Z33XQ" type="JAVA_METHOD" expression="setDestino">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FAygCkIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FAygC0IaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FAygDEIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FAygDUIaEfCOhu7W5Z33XQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FAygDkIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_j027GkIjEfCOhu7W5Z33XQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_562sYEIkEfCOhu7W5Z33XQ" name="newForm9" content="101576b2-ac48-431a-8e1b-89f994b90d0d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_j027GUIjEfCOhu7W5Z33XQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_3Es-oEIkEfCOhu7W5Z33XQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_3Es-oUIkEfCOhu7W5Z33XQ" name="destino" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_j027HEIjEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_JCXGgDGcEfC-4Z9zH4y95A" name="Serviços administrativos" actor="_QG9VMDGdEfC-4Z9zH4y95A">
        <elements xmi:type="process:StartEvent" xmi:id="_21aYcDGcEfC-4Z9zH4y95A" name="Produtos do fornecedor" outgoing="_6pz3IDGcEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_21aYcjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_21aYcTGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_21aYczGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_5vY2QDGcEfC-4Z9zH4y95A" name="Gateway 1" outgoing="_BdZDwDGdEfC-4Z9zH4y95A _CWgdEDGdEfC-4Z9zH4y95A _Cxl2kDGdEfC-4Z9zH4y95A" incoming="_6pz3IDGcEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5vY2QjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5vY2QTGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5vY2QzGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IN0OsDGdEfC-4Z9zH4y95A" name="Verificar  concordância encomenda-documento" outgoing="_V0Ny8DGdEfC-4Z9zH4y95A" incoming="_BdZDwDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_78j4cjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_78j4cTGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_78j4czGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_WvGtYjyfEfCfw76yGlE_oQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_WvGtYzyfEfCfw76yGlE_oQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WvGtZDyfEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_WvGtZTyfEfCfw76yGlE_oQ" name="encomendasInput.concordancia" content="encomendasInput?.concordancia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_WvGtZjyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_WvGtZzyfEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setConcordancia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_78j4dDGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_78j4dTGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_78j4djGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_78j4eDGcEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_78j4dzGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IN0OujGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_M5i2IDyiEfCfw76yGlE_oQ" name="newForm1" content="613953a5-134d-4024-853a-9a5b22be8a31" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IN0OuTGdEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_WvGtYDyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_WvGtYTyfEfCfw76yGlE_oQ" name="concordancia" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IN0OvDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_RAuOwDGdEfC-4Z9zH4y95A" name="Verificar quantidade" outgoing="_VBadADGdEfC-4Z9zH4y95A" incoming="_CWgdEDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8vnGAjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8vnGATGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8vnGAzGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_YuQhsjyfEfCfw76yGlE_oQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_YuQhszyfEfCfw76yGlE_oQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YuQhtDyfEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_YuQhtTyfEfCfw76yGlE_oQ" name="encomendasInput.quantidade" content="encomendasInput?.quantidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_YuQhtjyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_YuQhtzyfEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setQuantidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8vnGBDGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8vnGBTGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8vnGBjGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8vnGCDGcEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8vnGBzGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_RAuOyjGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_pRHIoDyiEfCfw76yGlE_oQ" name="newForm2" content="69cd46b8-2116-41a0-b0ab-d41ca7f7d380" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_RAuOyTGdEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_YuQhsDyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_YuQhsTyfEfCfw76yGlE_oQ" name="quantidade" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_RAuOzDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Rfa88DGdEfC-4Z9zH4y95A" name="Verificar estado aparente do produto" outgoing="_WfPs8DGdEfC-4Z9zH4y95A" incoming="_Cxl2kDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9xidETGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9xidEDGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9xidEjGcEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_ESu74jyjEfCfw76yGlE_oQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ESu74zyjEfCfw76yGlE_oQ" name="encomendas" content="encomendas" type="TYPE_VARIABLE" returnType="com.company.model.Encomendas">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ESu75DyjEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ESu75TyjEfCfw76yGlE_oQ" name="encomendasInput.aparencia" content="encomendasInput?.aparencia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ESu75jyjEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ESu75zyjEfCfw76yGlE_oQ" type="JAVA_METHOD" expression="setAparencia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9xidEzGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9xidFDGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9xidFTGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9xidFzGcEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9xidFjGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Rfa8-jGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_KupPYDyjEfCfw76yGlE_oQ" name="newForm4" content="c4325f5f-7f3f-46b8-abe1-32eb81b99a57" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Rfa8-TGdEfC-4Z9zH4y95A">
            <inputs xmi:type="process:ContractInput" xmi:id="_ESu74DyjEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ESu74TyjEfCfw76yGlE_oQ" name="aparencia" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Rfa8_DGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_UaHzgDGdEfC-4Z9zH4y95A" name="Gateway 2" outgoing="_lDeycDGdEfC-4Z9zH4y95A" incoming="_VBadADGdEfC-4Z9zH4y95A _V0Ny8DGdEfC-4Z9zH4y95A _WfPs8DGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UaHzgjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UaHzgTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UaHzgzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ajKOUDGdEfC-4Z9zH4y95A" name="Tudo Correto?" outgoing="_lZ_N8DGdEfC-4Z9zH4y95A __VzoADGjEfC-n5Sky3geQg" incoming="_lDeycDGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ajKOUjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ajKOUTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ajKOUzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_cAKX0DGdEfC-4Z9zH4y95A" name="Gateway 3" outgoing="_lvinMDGdEfC-4Z9zH4y95A _mGqGsDGdEfC-4Z9zH4y95A" incoming="_lZ_N8DGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cAKX0jGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cAKX0TGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cAKX0zGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_eUr_MDGdEfC-4Z9zH4y95A" name="Gateway4" outgoing="_nYSGoDGdEfC-4Z9zH4y95A" incoming="_meCr8DGdEfC-4Z9zH4y95A _m694gDGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eUsmQDGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eUr_MTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eUsmQTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_fbLGIDGdEfC-4Z9zH4y95A" name="End1" incoming="_nYSGoDGdEfC-4Z9zH4y95A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fbLGIjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fbLGITGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fbLGIzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_o7qk8DGdEfC-4Z9zH4y95A" name="Preencher nota não conformidade Sharepoint" outgoing="_meCr8DGdEfC-4Z9zH4y95A" incoming="_mGqGsDGdEfC-4Z9zH4y95A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dAFjwjGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dAFjwTGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dAFjwzGdEfC-4Z9zH4y95A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dAFjxDGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dAFjxTGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dAFjxjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dAFjyDGdEfC-4Z9zH4y95A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dAFjxzGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_o7qk-jGdEfC-4Z9zH4y95A">
            <targetForm xmi:type="expression:Expression" xmi:id="_tLT4oEIZEfCOhu7W5Z33XQ" name="NotaConformidade" content="f30e0b1b-24f1-493c-b0b8-24e7a6b33685" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_o7qk-TGdEfC-4Z9zH4y95A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_o7qk_DGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ie2ZYDycEfCfw76yGlE_oQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Tp7FJDyfEfCfw76yGlE_oQ" name="initEncomendas()" content="def encomendasVar = new com.company.model.Encomendas()&#xD;&#xA;encomendasVar.concordancia = encomendasInput?.concordancia&#xD;&#xA;encomendasVar.aparencia = encomendasInput?.aparencia&#xD;&#xA;encomendasVar.quantidade = encomendasInput?.quantidade&#xD;&#xA;return encomendasVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Encomendas">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Tp7FJTyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_jgdnYDycEfCfw76yGlE_oQ" name="armazenamento" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Armazenamento">
        <defaultValue xmi:type="expression:Expression" xmi:id="_UituUjyfEfCfw76yGlE_oQ" name="initArmazenamento()" content="def armazenamentoVar = new com.company.model.Armazenamento()&#xD;&#xA;armazenamentoVar.id_produto = armazenamentoInput?.id_produto&#xD;&#xA;return armazenamentoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Armazenamento">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_UituUzyfEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Hdk6EDGcEfC-4Z9zH4y95A">
        <targetForm xmi:type="expression:Expression" xmi:id="_H8KrAEIlEfCOhu7W5Z33XQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Hdk6EjGcEfC-4Z9zH4y95A">
        <targetForm xmi:type="expression:Expression" xmi:id="_Hdk6EzGcEfC-4Z9zH4y95A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6pz3IDGcEfC-4Z9zH4y95A" target="_5vY2QDGcEfC-4Z9zH4y95A" source="_21aYcDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6pz3ITGcEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_6pz3IjGcEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BdZDwDGdEfC-4Z9zH4y95A" target="_IN0OsDGdEfC-4Z9zH4y95A" source="_5vY2QDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BdZDwTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_BdZDwjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CWgdEDGdEfC-4Z9zH4y95A" target="_RAuOwDGdEfC-4Z9zH4y95A" source="_5vY2QDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CWgdETGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_CWgdEjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Cxl2kDGdEfC-4Z9zH4y95A" target="_Rfa88DGdEfC-4Z9zH4y95A" source="_5vY2QDGcEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Cxl2kTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Cxl2kjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VBadADGdEfC-4Z9zH4y95A" target="_UaHzgDGdEfC-4Z9zH4y95A" source="_RAuOwDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VBadATGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_VBadAjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V0Ny8DGdEfC-4Z9zH4y95A" target="_UaHzgDGdEfC-4Z9zH4y95A" source="_IN0OsDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V0Ny8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_V0Ny8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WfPs8DGdEfC-4Z9zH4y95A" target="_UaHzgDGdEfC-4Z9zH4y95A" source="_Rfa88DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WfPs8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_WfPs8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lDeycDGdEfC-4Z9zH4y95A" target="_ajKOUDGdEfC-4Z9zH4y95A" source="_UaHzgDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lDeycTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lDeycjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lZ_N8DGdEfC-4Z9zH4y95A" name="Não" target="_cAKX0DGdEfC-4Z9zH4y95A" source="_ajKOUDGdEfC-4Z9zH4y95A" isDefault="true" conditionType="DECISION_TABLE">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lZ_N8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lZ_N8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lvinMDGdEfC-4Z9zH4y95A" target="_EToUgEIZEfCOhu7W5Z33XQ" source="_cAKX0DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lvinMTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lvinMjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mGqGsDGdEfC-4Z9zH4y95A" target="_o7qk8DGdEfC-4Z9zH4y95A" source="_cAKX0DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mGqGsTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_mGqGsjGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_meCr8DGdEfC-4Z9zH4y95A" target="_eUr_MDGdEfC-4Z9zH4y95A" source="_o7qk8DGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_meCr8TGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_meCr8jGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_m694gDGdEfC-4Z9zH4y95A" target="_eUr_MDGdEfC-4Z9zH4y95A" source="_EToUgEIZEfCOhu7W5Z33XQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_m694gTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_m694gjGdEfC-4Z9zH4y95A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nYSGoDGdEfC-4Z9zH4y95A" target="_fbLGIDGdEfC-4Z9zH4y95A" source="_eUr_MDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nYSGoTGdEfC-4Z9zH4y95A"/>
        <condition xmi:type="expression:Expression" xmi:id="_nYSGojGdEfC-4Z9zH4y95A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__VzoADGjEfC-n5Sky3geQg" name="Sim" target="_j027EEIjEfCOhu7W5Z33XQ" source="_ajKOUDGdEfC-4Z9zH4y95A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__VzoATGjEfC-n5Sky3geQg"/>
        <condition xmi:type="expression:Expression" xmi:id="__VzoAjGjEfC-n5Sky3geQg" name="VerificaçãoEncomenda" content="encomendas.concordancia == true &amp;&amp;&#xD;&#xA;encomendas.aparencia == true &amp;&amp;&#xD;&#xA;encomendas.quantidade == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pl2n8EIfEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_C5oUEjGkEfC-n5Sky3geQg" name="Stock" target="_1klxoDyQEfCJUObNuNZMMQ" source="_-dAXwDGjEfC-n5Sky3geQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_C5oUEzGkEfC-n5Sky3geQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_C5oUFDGkEfC-n5Sky3geQg" name="newScript()" content="encomendas.destino == &quot;Stock&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4s1sAEIiEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DvbTpzGkEfC-n5Sky3geQg" name="Cliente" target="_DvaskDGkEfC-n5Sky3geQg" source="_-dAXwDGjEfC-n5Sky3geQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DvbTqDGkEfC-n5Sky3geQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_DvbTqTGkEfC-n5Sky3geQg" name="cliente" content="encomendas.destino == &quot;Cliente&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6hjx8EIiEfCOhu7W5Z33XQ" name="encomendas" dataType="_9Wz_NDGTEfCkYdaGFVhtZg" className="com.company.model.Encomendas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_II5gcEIaEfCOhu7W5Z33XQ" target="_-dAXwDGjEfC-n5Sky3geQg" source="_j027EEIjEfCOhu7W5Z33XQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_II6HgEIaEfCOhu7W5Z33XQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_II6HgUIaEfCOhu7W5Z33XQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QG9VMDGdEfC-4Z9zH4y95A" name="Serviços administrativos" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_2XLAcDGgEfCnSJk-yp4Knw" name="Técnico de área de operações"/>
      <contract xmi:type="process:Contract" xmi:id="_Hdk6FDGcEfC-4Z9zH4y95A">
        <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FIDyfEfCfw76yGlE_oQ" name="encomendasInput" type="COMPLEX" dataReference="encomendas">
          <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FITyfEfCfw76yGlE_oQ" name="concordancia" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FIjyfEfCfw76yGlE_oQ" name="aparencia" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_Tp7FIzyfEfCfw76yGlE_oQ" name="quantidade" type="BOOLEAN"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_UituUDyfEfCfw76yGlE_oQ" name="armazenamentoInput" type="COMPLEX" dataReference="armazenamento">
          <inputs xmi:type="process:ContractInput" xmi:id="_UituUTyfEfCfw76yGlE_oQ" name="id_produto" type="INTEGER"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6ATGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6AjGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6AzGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6BDGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6BTGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6BjGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6BzGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6CDGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6CTGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6CjGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6CzGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6DDGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Hdk6DTGcEfC-4Z9zH4y95A">
        <name xmi:type="expression:Expression" xmi:id="_Hdk6DjGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Hdk6DzGcEfC-4Z9zH4y95A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_9Wz_LDGTEfCkYdaGFVhtZg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_9Wz_LTGTEfCkYdaGFVhtZg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_9Wz_LjGTEfCkYdaGFVhtZg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_9Wz_LzGTEfCkYdaGFVhtZg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_9Wz_MDGTEfCkYdaGFVhtZg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_9Wz_MTGTEfCkYdaGFVhtZg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_9Wz_MjGTEfCkYdaGFVhtZg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_9Wz_MzGTEfCkYdaGFVhtZg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_9Wz_NDGTEfCkYdaGFVhtZg" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_LodmkDyTEfCJUObNuNZMMQ" name="Msg" target="_SNvGYDGbEfC-4Z9zH4y95A" source="_DvaskDGkEfC-n5Sky3geQg"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_9Wz_NTGTEfCkYdaGFVhtZg" type="Process" element="_9Wz_ADGTEfCkYdaGFVhtZg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_9Wz_NjGTEfCkYdaGFVhtZg" type="2007" element="_9Wz_ATGTEfCkYdaGFVhtZg">
      <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_NzGTEfCkYdaGFVhtZg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_ODGTEfCkYdaGFVhtZg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_9Wz_OTGTEfCkYdaGFVhtZg" type="3007" element="_9Wz_AjGTEfCkYdaGFVhtZg">
          <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_OjGTEfCkYdaGFVhtZg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_OzGTEfCkYdaGFVhtZg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_9Wz_PDGTEfCkYdaGFVhtZg" type="3005" element="_9Wz_BzGTEfCkYdaGFVhtZg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9Wz_PTGTEfCkYdaGFVhtZg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Wz_PjGTEfCkYdaGFVhtZg" x="182" y="100" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SNvtczGbEfC-4Z9zH4y95A" type="3012" element="_SNvGYDGbEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SNwUgDGbEfC-4Z9zH4y95A" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SNwUgTGbEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SNvtdDGbEfC-4Z9zH4y95A" x="62" y="114"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wjF7TDGbEfC-4Z9zH4y95A" type="3005" element="_wjFUMDGbEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wjGiUDGbEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wjF7TTGbEfC-4Z9zH4y95A" x="434" y="100" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w3bznTGbEfC-4Z9zH4y95A" type="3005" element="_w3bzkDGbEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_w3bznzGbEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w3bznjGbEfC-4Z9zH4y95A" x="655" y="100" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VW9FITyTEfCJUObNuNZMMQ" type="3003" element="_VW8eEDyTEfCJUObNuNZMMQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VW9FIzyTEfCJUObNuNZMMQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VW9FJDyTEfCJUObNuNZMMQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VW9FIjyTEfCJUObNuNZMMQ" x="1430" y="116" width="28" height="28"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_9Wz_QzGTEfCkYdaGFVhtZg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_9Wz_RDGTEfCkYdaGFVhtZg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_9Wz_RTGTEfCkYdaGFVhtZg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_9Wz_RjGTEfCkYdaGFVhtZg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Wz_RzGTEfCkYdaGFVhtZg"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_9Wz_SDGTEfCkYdaGFVhtZg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_9Wz_STGTEfCkYdaGFVhtZg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_9Wz_SjGTEfCkYdaGFVhtZg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_9Wz_SzGTEfCkYdaGFVhtZg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Wz_TDGTEfCkYdaGFVhtZg" width="1620" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_eu2dkzGbEfC-4Z9zH4y95A" type="2007" element="_eu12gDGbEfC-4Z9zH4y95A">
      <children xmi:type="notation:DecorationNode" xmi:id="_eu2dmDGbEfC-4Z9zH4y95A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_eu2dmTGbEfC-4Z9zH4y95A" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_wLCnoTGbEfC-4Z9zH4y95A" type="3005" element="_wLCAkDGbEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_wLCnozGbEfC-4Z9zH4y95A" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wLCnojGbEfC-4Z9zH4y95A" x="209" y="84" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_1d0v7TGbEfC-4Z9zH4y95A" type="3005" element="_1d0v4DGbEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_1d0v7zGbEfC-4Z9zH4y95A" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1d0v7jGbEfC-4Z9zH4y95A" x="450" y="84" width="124" height="62"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_3Sa6AzGbEfC-4Z9zH4y95A" type="3003" element="_3SaS8DGbEfC-4Z9zH4y95A" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_3Sa6BTGbEfC-4Z9zH4y95A" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_3Sa6BjGbEfC-4Z9zH4y95A" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3Sa6BDGbEfC-4Z9zH4y95A" x="1457" y="101"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_r9B18DyaEfCfw76yGlE_oQ" type="3002" element="_r9An0DyaEfCfw76yGlE_oQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_r9B18jyaEfCfw76yGlE_oQ" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_r9B18zyaEfCfw76yGlE_oQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r9B18TyaEfCfw76yGlE_oQ" x="91" y="99" width="30" height="30"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_eu2dlDGbEfC-4Z9zH4y95A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_eu2dlTGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_eu2dljGbEfC-4Z9zH4y95A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_eu2dmjGbEfC-4Z9zH4y95A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eu2dlzGbEfC-4Z9zH4y95A" width="1620" height="271"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_HdlhEDGcEfC-4Z9zH4y95A" type="2007" element="_Hdk6ADGcEfC-4Z9zH4y95A">
      <children xmi:type="notation:DecorationNode" xmi:id="_HdlhFTGcEfC-4Z9zH4y95A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_HdlhFjGcEfC-4Z9zH4y95A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_IDhfsDGcEfC-4Z9zH4y95A" type="3007" element="_IDg4oDGcEfC-4Z9zH4y95A">
          <children xmi:type="notation:DecorationNode" xmi:id="_IDhftTGcEfC-4Z9zH4y95A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IDhftjGcEfC-4Z9zH4y95A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_-dA-0DGjEfC-n5Sky3geQg" type="3008" element="_-dAXwDGjEfC-n5Sky3geQg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-dA-0jGjEfC-n5Sky3geQg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-dA-0zGjEfC-n5Sky3geQg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-dA-0TGjEfC-n5Sky3geQg" x="1022" y="44"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DvbTozGkEfC-n5Sky3geQg" type="3011" element="_DvaskDGkEfC-n5Sky3geQg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DvbTpTGkEfC-n5Sky3geQg" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DvbTpjGkEfC-n5Sky3geQg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DvbTpDGkEfC-n5Sky3geQg" x="1430" y="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1klxpDyQEfCJUObNuNZMMQ" type="3011" element="_1klxoDyQEfCJUObNuNZMMQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1kmYsDyQEfCJUObNuNZMMQ" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1kmYsTyQEfCJUObNuNZMMQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1klxpTyQEfCJUObNuNZMMQ" x="1432" y="22" width="28" height="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ETo7kEIZEfCOhu7W5Z33XQ" type="3005" element="_EToUgEIZEfCOhu7W5Z33XQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ETo7kkIZEfCOhu7W5Z33XQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ETo7kUIZEfCOhu7W5Z33XQ" x="1015" y="153" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_j027HUIjEfCOhu7W5Z33XQ" type="3005" element="_j027EEIjEfCOhu7W5Z33XQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j027H0IjEfCOhu7W5Z33XQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j027HkIjEfCOhu7W5Z33XQ" x="830" y="33" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IDhfsTGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IDhfsjGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IDhfszGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IDhftzGcEfC-4Z9zH4y95A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IDhftDGcEfC-4Z9zH4y95A" x="53" y="10" width="1649" height="272"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_JCXGgTGcEfC-4Z9zH4y95A" type="3007" element="_JCXGgDGcEfC-4Z9zH4y95A">
          <children xmi:type="notation:DecorationNode" xmi:id="_JCXGhjGcEfC-4Z9zH4y95A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_JCXtkDGcEfC-4Z9zH4y95A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_21aYdDGcEfC-4Z9zH4y95A" type="3002" element="_21aYcDGcEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_21a_gDGcEfC-4Z9zH4y95A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_21a_gTGcEfC-4Z9zH4y95A" x="25" y="31"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_21aYdTGcEfC-4Z9zH4y95A" x="77" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5vZdUDGcEfC-4Z9zH4y95A" type="3009" element="_5vY2QDGcEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5vZdUjGcEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5vZdUzGcEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5vZdUTGcEfC-4Z9zH4y95A" x="224" y="103"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IN0OvTGdEfC-4Z9zH4y95A" type="3005" element="_IN0OsDGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IN0OvzGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IN0OvjGdEfC-4Z9zH4y95A" x="346" y="16" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RAuOzTGdEfC-4Z9zH4y95A" type="3005" element="_RAuOwDGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RAuOzzGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAuOzjGdEfC-4Z9zH4y95A" x="347" y="101" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RfbkADGdEfC-4Z9zH4y95A" type="3005" element="_Rfa88DGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RfbkAjGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfbkATGdEfC-4Z9zH4y95A" x="346" y="187" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UaHzhDGdEfC-4Z9zH4y95A" type="3009" element="_UaHzgDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UaHzhjGdEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UaHzhzGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UaHzhTGdEfC-4Z9zH4y95A" x="593" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ajKOVDGdEfC-4Z9zH4y95A" type="3008" element="_ajKOUDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ajK1YDGdEfC-4Z9zH4y95A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ajK1YTGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ajKOVTGdEfC-4Z9zH4y95A" x="758" y="16"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cAK-4DGdEfC-4Z9zH4y95A" type="3009" element="_cAKX0DGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_cAK-4jGdEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_cAK-4zGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cAK-4TGdEfC-4Z9zH4y95A" x="905" y="16"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eUsmQjGdEfC-4Z9zH4y95A" type="3009" element="_eUr_MDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eUsmRDGdEfC-4Z9zH4y95A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eUsmRTGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eUsmQzGdEfC-4Z9zH4y95A" x="1163" y="16"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fbLGJDGdEfC-4Z9zH4y95A" type="3003" element="_fbLGIDGdEfC-4Z9zH4y95A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fbLtMDGdEfC-4Z9zH4y95A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fbLtMTGdEfC-4Z9zH4y95A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fbLGJTGdEfC-4Z9zH4y95A" x="1429" y="22"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o7qk_TGdEfC-4Z9zH4y95A" type="3005" element="_o7qk8DGdEfC-4Z9zH4y95A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_o7rMADGdEfC-4Z9zH4y95A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o7qk_jGdEfC-4Z9zH4y95A" x="991" y="85" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_JCXGgjGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_JCXGgzGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_JCXGhDGcEfC-4Z9zH4y95A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_JCXtkTGcEfC-4Z9zH4y95A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JCXGhTGcEfC-4Z9zH4y95A" x="48" y="250" width="1297" height="307"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_HdlhETGcEfC-4Z9zH4y95A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_HdlhEjGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_HdlhEzGcEfC-4Z9zH4y95A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_HdlhFzGcEfC-4Z9zH4y95A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HdlhFDGcEfC-4Z9zH4y95A" width="1677" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_9Wz_TTGTEfCkYdaGFVhtZg"/>
    <edges xmi:type="notation:Connector" xmi:id="_yBJVAzGYEfC-4Z9zH4y95A" type="4001" element="_yBJVADGYEfC-4Z9zH4y95A" source="_9Wz_PDGTEfCkYdaGFVhtZg" target="_wjF7TDGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yBJVBjGYEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yBJVBzGYEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yBJVBDGYEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yBJVBTGYEfC-4Z9zH4y95A" points="[60, -2, -194, 3]$[194, -2, -60, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S6TRczGbEfC-4Z9zH4y95A" type="4001" element="_S6TRcDGbEfC-4Z9zH4y95A" source="_SNvtczGbEfC-4Z9zH4y95A" target="_9Wz_PDGTEfCkYdaGFVhtZg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S6T4gDGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S6T4gTGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S6TRdDGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S6TRdTGbEfC-4Z9zH4y95A" points="[-1, -15, -99, -14]$[90, -15, -8, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S6VGoDGbEfC-4Z9zH4y95A" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S6VGoTGbEfC-4Z9zH4y95A" id="(0.07,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WIo1szGbEfC-4Z9zH4y95A" type="4001" element="_WIo1sDGbEfC-4Z9zH4y95A" source="_wjF7TDGbEfC-4Z9zH4y95A" target="_w3bznTGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WIo1tjGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WIo1tzGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WIo1tDGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WIo1tTGbEfC-4Z9zH4y95A" points="[60, -2, -161, -2]$[161, -2, -60, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_a5RTIzGbEfC-4Z9zH4y95A" type="4001" element="_a5RTIDGbEfC-4Z9zH4y95A" source="_w3bznTGbEfC-4Z9zH4y95A" target="_VW9FITyTEfCJUObNuNZMMQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_a5RTJjGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_a5RTJzGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_a5RTJDGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_a5RTJTGbEfC-4Z9zH4y95A" points="[60, -3, -166, 2]$[211, -3, -15, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ul5OxDGbEfC-4Z9zH4y95A" type="4001" element="_ul5OwTGbEfC-4Z9zH4y95A" source="_r9B18DyaEfCfw76yGlE_oQ" target="_wLCnoTGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ul5OxzGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ul5OyDGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ul5OxTGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ul5OxjGbEfC-4Z9zH4y95A" points="[14, -2, -149, -2]$[103, -2, -60, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0oRn8jGbEfC-4Z9zH4y95A" type="4001" element="_0oRA7DGbEfC-4Z9zH4y95A" source="_wLCnoTGbEfC-4Z9zH4y95A" target="_1d0v7TGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0oRn9TGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0oRn9jGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0oRn8zGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0oRn9DGbEfC-4Z9zH4y95A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5jKNkjGbEfC-4Z9zH4y95A" type="4001" element="_5jJmgDGbEfC-4Z9zH4y95A" source="_1d0v7TGbEfC-4Z9zH4y95A" target="_3Sa6AzGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5jKNlTGbEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5jKNljGbEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5jKNkzGbEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5jKNlDGbEfC-4Z9zH4y95A" points="[0, 17, -395, 14]$[390, 17, -5, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5jK0oDGbEfC-4Z9zH4y95A" id="(1.0,0.48)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6p0eMDGcEfC-4Z9zH4y95A" type="4001" element="_6pz3IDGcEfC-4Z9zH4y95A" source="_21aYdDGcEfC-4Z9zH4y95A" target="_5vZdUDGcEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6p0eMzGcEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6p0eNDGcEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6p0eMTGcEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6p0eMjGcEfC-4Z9zH4y95A" points="[-2, -6, -140, 5]$[142, 7, 4, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6p1sUDGcEfC-4Z9zH4y95A" id="(1.0,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BdZq0DGdEfC-4Z9zH4y95A" type="4001" element="_BdZDwDGdEfC-4Z9zH4y95A" source="_5vZdUDGcEfC-4Z9zH4y95A" target="_IN0OvTGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BdZq0zGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BdZq1DGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BdZq0TGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BdZq0jGdEfC-4Z9zH4y95A" points="[-22, -30, -108, 65]$[-22, -89, -108, 6]$[79, -89, -7, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BdaR4DGdEfC-4Z9zH4y95A" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BdaR4TGdEfC-4Z9zH4y95A" id="(0.07,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CWgdEzGdEfC-4Z9zH4y95A" type="4001" element="_CWgdEDGdEfC-4Z9zH4y95A" source="_5vZdUDGcEfC-4Z9zH4y95A" target="_RAuOzTGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CWgdFjGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CWhEIDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CWgdFDGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CWgdFTGdEfC-4Z9zH4y95A" points="[-2, -4, -102, 0]$[79, -4, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CWhrMDGdEfC-4Z9zH4y95A" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CWhrMTGdEfC-4Z9zH4y95A" id="(0.21,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CxmdoDGdEfC-4Z9zH4y95A" type="4001" element="_Cxl2kDGdEfC-4Z9zH4y95A" source="_5vZdUDGcEfC-4Z9zH4y95A" target="_RfbkADGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CxmdozGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CxmdpDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CxmdoTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CxmdojGdEfC-4Z9zH4y95A" points="[-22, 15, -117, -72]$[-22, 80, -117, -7]$[79, 80, -16, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CxnEsDGdEfC-4Z9zH4y95A" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CxnEsTGdEfC-4Z9zH4y95A" id="(0.16,0.62)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VBbEEDGdEfC-4Z9zH4y95A" type="4001" element="_VBadADGdEfC-4Z9zH4y95A" source="_RAuOzTGdEfC-4Z9zH4y95A" target="_UaHzhDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VBbEEzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VBbEFDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VBbEETGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VBbEEjGdEfC-4Z9zH4y95A" points="[0, 0, -137, -28]$[127, 27, -10, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VBbrIDGdEfC-4Z9zH4y95A" id="(1.0,0.4166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VBbrITGdEfC-4Z9zH4y95A" id="(0.23255813953488372,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V0Ny8zGdEfC-4Z9zH4y95A" type="4001" element="_V0Ny8DGdEfC-4Z9zH4y95A" source="_IN0OvTGdEfC-4Z9zH4y95A" target="_UaHzhDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V0Ny9jGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V0Ny9zGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V0Ny9DGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V0Ny9TGdEfC-4Z9zH4y95A" points="[0, 0, -128, -87]$[126, 0, -2, -87]$[126, 68, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_V0PBEDGdEfC-4Z9zH4y95A" id="(1.0,0.38571428571428573)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WfPs8zGdEfC-4Z9zH4y95A" type="4001" element="_WfPs8DGdEfC-4Z9zH4y95A" source="_RfbkADGdEfC-4Z9zH4y95A" target="_UaHzhDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WfPs9jGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WfPs9zGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WfPs9DGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WfPs9TGdEfC-4Z9zH4y95A" points="[0, 2, -148, 86]$[146, 2, -2, 86]$[146, -65, -2, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WfQUADGdEfC-4Z9zH4y95A" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lDfZgDGdEfC-4Z9zH4y95A" type="4001" element="_lDeycDGdEfC-4Z9zH4y95A" source="_UaHzhDGdEfC-4Z9zH4y95A" target="_ajKOVDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lDfZgzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lDfZhDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lDfZgTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lDfZgjGdEfC-4Z9zH4y95A" points="[-14, 8, -157, 106]$[147, -80, 4, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lDgAkDGdEfC-4Z9zH4y95A" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_laAcEDGdEfC-4Z9zH4y95A" type="4001" element="_lZ_N8DGdEfC-4Z9zH4y95A" source="_ajKOVDGdEfC-4Z9zH4y95A" target="_cAK-4DGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_laAcEzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_laAcFDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_laAcETGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_laAcEjGdEfC-4Z9zH4y95A" points="[-8, 0, -133, 7]$[123, -26, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_laBDIDGdEfC-4Z9zH4y95A" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lvjOQDGdEfC-4Z9zH4y95A" type="4001" element="_lvinMDGdEfC-4Z9zH4y95A" source="_cAK-4DGdEfC-4Z9zH4y95A" target="_ETo7kEIZEfCOhu7W5Z33XQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lvjOQzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lvj1UDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lvjOQTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lvjOQjGdEfC-4Z9zH4y95A" points="[-12, -16, -84, 101]$[63, -118, -9, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lvkcYDGdEfC-4Z9zH4y95A" id="(0.4883720930232558,0.023255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lvkcYTGdEfC-4Z9zH4y95A" id="(0.09,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mGqtwDGdEfC-4Z9zH4y95A" type="4001" element="_mGqGsDGdEfC-4Z9zH4y95A" source="_cAK-4DGdEfC-4Z9zH4y95A" target="_o7qk_TGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mGqtwzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mGqtxDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mGqtwTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mGqtwjGdEfC-4Z9zH4y95A" points="[-22, 20, -93, -52]$[-22, 80, -93, 8]$[43, 80, -28, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mGrU0DGdEfC-4Z9zH4y95A" id="(1.0,0.5348837209302325)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mGrU0TGdEfC-4Z9zH4y95A" id="(0.2,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_meDTADGdEfC-4Z9zH4y95A" type="4001" element="_meCr8DGdEfC-4Z9zH4y95A" source="_o7qk_TGdEfC-4Z9zH4y95A" target="_eUsmQjGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_meDTAzGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_meDTBDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_meDTATGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_meDTAjGdEfC-4Z9zH4y95A" points="[0, 0, -73, 75]$[67, -60, -6, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_meD6EDGdEfC-4Z9zH4y95A" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_m694gzGdEfC-4Z9zH4y95A" type="4001" element="_m694gDGdEfC-4Z9zH4y95A" source="_ETo7kEIZEfCOhu7W5Z33XQ" target="_eUsmQjGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_m694hjGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_m694hzGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_m694hDGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_m694hTGdEfC-4Z9zH4y95A" points="[0, 0, -92, -109]$[90, 90, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_m6-fkDGdEfC-4Z9zH4y95A" id="(1.0,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nYStsDGdEfC-4Z9zH4y95A" type="4001" element="_nYSGoDGdEfC-4Z9zH4y95A" source="_eUsmQjGdEfC-4Z9zH4y95A" target="_fbLGJDGdEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nYStszGdEfC-4Z9zH4y95A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nYSttDGdEfC-4Z9zH4y95A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nYStsTGdEfC-4Z9zH4y95A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nYStsjGdEfC-4Z9zH4y95A" points="[-14, 6, -186, 0]$[157, 6, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nYTUwDGdEfC-4Z9zH4y95A" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__V02IDGjEfC-n5Sky3geQg" type="4001" element="__VzoADGjEfC-n5Sky3geQg" source="_ajKOVDGdEfC-4Z9zH4y95A" target="_j027HUIjEfCOhu7W5Z33XQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__V02IzGjEfC-n5Sky3geQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__V02JDGjEfC-n5Sky3geQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__V02ITGjEfC-n5Sky3geQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__V02IjGjEfC-n5Sky3geQg" points="[0, -21, -247, 214]$[0, -225, -247, 10]$[246, -225, -1, 10]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__V2EQTGjEfC-n5Sky3geQg" id="(0.03571428571428571,0.37142857142857144)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_C5oUFTGkEfC-n5Sky3geQg" type="4001" element="_C5oUEjGkEfC-n5Sky3geQg" source="_-dA-0DGjEfC-n5Sky3geQg" target="_1klxpDyQEfCJUObNuNZMMQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_C5oUGDGkEfC-n5Sky3geQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_C5oUGTGkEfC-n5Sky3geQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_C5oUFjGkEfC-n5Sky3geQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_C5oUFzGkEfC-n5Sky3geQg" points="[0, -21, -403, 8]$[0, -30, -403, -1]$[389, -30, -14, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Dvb6sDGkEfC-n5Sky3geQg" type="4001" element="_DvbTpzGkEfC-n5Sky3geQg" source="_-dA-0DGjEfC-n5Sky3geQg" target="_DvbTozGkEfC-n5Sky3geQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Dvb6szGkEfC-n5Sky3geQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Dvb6tDGkEfC-n5Sky3geQg" x="-3" y="31"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Dvb6sTGkEfC-n5Sky3geQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Dvb6sjGkEfC-n5Sky3geQg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LoeNoDyTEfCJUObNuNZMMQ" type="4002" element="_LodmkDyTEfCJUObNuNZMMQ" source="_DvbTozGkEfC-n5Sky3geQg" target="_SNvtczGbEfC-4Z9zH4y95A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LoeNozyTEfCJUObNuNZMMQ" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LoeNpDyTEfCJUObNuNZMMQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LoeNoTyTEfCJUObNuNZMMQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LoeNojyTEfCJUObNuNZMMQ" points="[14, -1, 1190, 542]$[225, -1, 1401, 542]$[225, -462, 1401, 81]$[-1176, -462, 0, 81]$[-1176, -529, 0, 14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_II6HgkIaEfCOhu7W5Z33XQ" type="4001" element="_II5gcEIaEfCOhu7W5Z33XQ" source="_j027HUIjEfCOhu7W5Z33XQ" target="_-dA-0DGjEfC-n5Sky3geQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_II6ukEIaEfCOhu7W5Z33XQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_II6ukUIaEfCOhu7W5Z33XQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_II6Hg0IaEfCOhu7W5Z33XQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_II6HhEIaEfCOhu7W5Z33XQ" points="[0, 3, -56, 0]$[53, 3, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_II7VoEIaEfCOhu7W5Z33XQ" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_II7VoUIaEfCOhu7W5Z33XQ" id="(0.09302325581395349,0.5116279069767442)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
